heyverse/hey

- src/components/Shared/Attachment.tsx
Removed non-null assertion usage.
Fixes [JS-0339](https://deepsource.io/gh/lensterxyz/lenster/issue/JS-0339/occurrences).
> fix: forbidden non-null assertion usage

- src/components/Post/Actions/index.tsx
Elements with the `button` interactive role must be tabbable
Resolves [JS-0751](https://deepsource.io/gh/lensterxyz/lenster/issue/JS-0751/occurrences)
> fix: focus interactive elements

- .eslintrc
- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/feature_request.yml
- cypress.config.ts
- package.json
- src/components/Comment/NewComment/index.tsx
- src/components/Community/Create.tsx
- src/components/Community/Join.tsx
- src/components/Crowdfund/Create.tsx
- src/components/Post/Actions/Collect/CollectModule.tsx
- src/components/Post/Actions/Mirror.tsx
- src/components/Post/Actions/index.tsx
- src/components/Post/Crowdfund/Fund.tsx
- src/components/Post/NewPost/index.tsx
- src/components/Settings/Account/SetProfile.tsx
- src/components/Settings/Account/SuperFollow.tsx
- src/components/Settings/Allowance/Button.tsx
- src/components/Settings/Delete/index.tsx
- src/components/Settings/Profile/NFTPicture.tsx
- src/components/Settings/Profile/Picture.tsx
- src/components/Settings/Profile/Profile.tsx
- src/components/Shared/Attachment.tsx
- src/components/Shared/Follow.tsx
- src/components/Shared/Navbar/Search.tsx
- src/components/Shared/Navbar/index.tsx
- src/components/Shared/SelectCollectModule/FeeEntry.tsx
- src/components/Shared/SuperFollow/FollowModule.tsx
- src/pages/_app.tsx
- yarn.lock
> main => testnet

- src/components/Post/index.tsx
- src/lib/getAttribute.ts
> fix: template literals having non-string type

- src/components/UI/Input.tsx
Remove purple input ring when error and focused
Related to:
https://github.com/lensterxyz/lenster/issues/68
https://github.com/lensterxyz/lenster/pull/173
https://github.com/lensterxyz/lenster/pull/177
https://github.com/lensterxyz/lenster/pull/173#discussion_r933920236
> fix: remove input ring on error and focus

- src/components/Crowdfund/Create.tsx
- src/components/Settings/Account/SuperFollow.tsx
- src/components/Settings/Profile/NFTPicture.tsx
- src/components/Settings/Profile/Profile.tsx
- src/components/Shared/Navbar/Login/Create/index.tsx
- src/constants.ts
- src/lib/formatAddress.ts
> fix: website validation

- .eslintrc
It is better to add [`no-unexpected-multiline`](https://eslint.org/docs/latest/rules/no-unexpected-multiline) rule, since we are not using semicolons.
> chore: add `no-unexpected-multiline` rule

- src/components/Publication/Actions/index.tsx
- src/components/Publication/FullPublication.tsx
- src/components/Publication/SinglePublication.tsx
- src/components/Publication/ThreadBody.tsx
> chore: rename PostActions component to PublicationActions

- src/components/Publication/Actions/Menu/index.tsx
- src/components/Publication/Actions/index.tsx
> chore: rename PostMenu component to PublicationMenu

- src/components/Shared/Giphy/GifSelector.tsx
> fix: margin in gif search

- src/components/Shared/Footer.tsx
> feat: add copyright year in footer

- src/components/Layout.tsx
- src/components/Settings/Delete/index.tsx
- src/components/Shared/Navbar/SignedUser.tsx
- src/components/Shared/Navbar/UnsignedUser.tsx
> refactor: useEffect in layout

- next.config.js
> chore: add swcMinify

- src/components/Settings/Allowance/Button.tsx
Hey, following up on https://lenster.xyz/posts/0x242d-0x21 now that Lenster's open source ;-) I've tweaked the entire text line but, either way, "detected" definitely needs to become "deducted".
> Collect Module warning text tweak (trivial, and important)

- src/components/Shared/Video.tsx
This adds the functionality of auto pausing video when scrolling and video leaves viewport.
Due to refs not working well with the plyr object combined with the intersectionobserver, using a ref on the wrapper for detecting the location of the player in relation to viewport, then a ref on the player to control it.
https://user-images.githubusercontent.com/5845181/186959474-e5d19f50-5599-4a00-bee2-6439a07b241c.mov
This can be tested by running and scrolling home until you find a video. Play the video, then scroll away. The video should pause. No other functionality should change.
> fix: add auto pausing video when video player leaves viewport

- src/components/Notification/List.tsx
Fixes the notifications infinite scroll.
The root cause is the way `IntersectionObserver` works. 
Right now we have 1000% root margin set so it's `10 * viewport height` which means the `loading` indicator is always in the intersection observer boundaries and `onEnter` callback is called just once.
Some may think that changing the `rootMargin` would solve the problem but in reality it's hard to predict given as when you set the `rootMargin` to let's say for .e.g `200%` (so twice the viewport height) it may works properly for some items (especially the one that take a lot of `height`) but will not cover all use cases. 
The proper fix given the current library in use `react-cool-inview` is to attach observer to the last item in the list. Every call to `fetchMore` the last item `ref` would …
> Fix notifications infinite scroll behaviour

- src/components/Shared/Attachments.tsx
Removes console.log from `Attachments` component
> chore: remove console

- src/lib/getTags.ts
Fixed deepsource's `Consider using let or const instead of var
JS-0239` issue
Resolves [JS-0239](https://deepsource.io/gh/lensterxyz/lenster/issue/JS-0239/occurrences?listindex=0)
> chore: prefer let/const

- src/components/Explore/FeedType.tsx
- src/components/Explore/index.tsx
> fix: text color and bg of explore tab in dark mode

- src/lib/uploadMediaToIPFS.ts
1. Included `Promise.all` 
2. All Promises will run concurrently instead of one after another
3. Fixes - Found `await` inside of loops - [JS-0032](https://deepsource.io/gh/lensterxyz/lenster/issue/JS-0032/occurrences?listindex=0)
Ref: https://www.techiediaries.com/promise-all-map-async-await-example/
- I haven't tested the changes in production
> chore: Unexpected `await` inside a loop

- src/components/Shared/Markup.tsx
- src/components/utils/matchers/markdown/MDLinkMatcher.tsx
Fixes [#35](https://github.com/lensterxyz/lenster/issues/35)
- Have utilized existing interweave markups to match for the `[Markdown Guide](https://www.markdownguide.org)` pattern
https://user-images.githubusercontent.com/65915812/196354829-d0f295df-613b-435f-9c9b-449c0fa96aa6.mov
> feat: markdown links support

- src/components/utils/hooks/useSendMessage.tsx
Use a try/catch to determine whether we want to toast a message failed to send error instead of a null check.
Fixes #886
> chore: remove == null check

- src/components/Composer/Post/New.tsx
- src/components/Messages/PreviewList.tsx
Added missing `type` attribute in button elements
Fixes #887
> chore: add missing type attribute in button elements

- src/components/utils/hooks/useXmtpClient.tsx
This PR uses XMTP's `production` environment on mainnet and `dev` on testnet. Note: you'll have to re-sign after this since we're now storing creds per env. Also, mainnet messages will be reset.
- Ensure messages are still visible on testnet after another sig.
> chore: use production messaging env on mainnet

- src/components/Messages/MessagesList.tsx
This PR updates our UI to insert the date divider when the date changes so that it now shows the messages for the given date below the divider. This matches how other messaging platforms render their dividers like Signal and will likely feel more intuitive.
| Before | After |
|--|--|
| <img width="831" alt="before" src="https://user-images.githubusercontent.com/556051/197234544-c2a2a688-adfe-4943-b1f2-3c4e31877c98.png">| <img width="823" alt="after" src="https://user-images.githubusercontent.com/556051/197234594-52fe1d84-22c9-4630-b160-53fb0cefc9d8.png">|
> fix: insert date divider before date's messages

- src/components/Home/EnableMessages.tsx
- src/components/utils/hooks/useGetConversation.tsx
- src/components/utils/hooks/useXmtpClient.tsx
- src/constants.ts
I noticed that while the client SDK is set to the production network, some of the checks for whether a user is on the network were always set to the dev network. This is causing errors when trying to message a profile that is active on one network but not the other.
> chore: set XMTP environment consistently

- src/components/Home/EnableMessages.tsx
- src/components/Messages/MessagesList.tsx
Updates the copy in the two enable DMs panels.
| Home | Messaging |
|--|--|
| <img width="1497" alt="Screen Shot 2022-10-24 at 10 07 25 AM" src="https://user-images.githubusercontent.com/556051/197546809-fe9bfe61-bcaf-4958-9540-4a5500d68a18.png"> |  <img width="835" alt="Screen Shot 2022-10-24 at 10 08 30 AM" src="https://user-images.githubusercontent.com/556051/197546874-5823500e-a573-45ef-975c-a52d505a96df.png"> |
> chore: update copy around enabling dms

- src/components/Messages/MessagesList.tsx
This PR removes the padding from the message list and instead adds top margin to the loading & end of list components. This allows the list to scroll under the header directly.
Fixes #911
> fix: remove fixed padding from top of message list

- src/components/utils/hooks/useXmtpClient.tsx
Include the `env` option with XMTP `Client.getKeys` call, so that it's using the correct network.
> fix: xmtp env mismatch

- src/components/Messages/Preview.tsx
- src/constants.ts
Adds an ellipsis if the name or message content is too long in the preview list.
| Before | After |
|--|--|
| <img width="374" alt="Screen Shot 2022-10-27 at 11 50 36 AM" src="https://user-images.githubusercontent.com/556051/198338676-ba57379a-68d6-45e3-9475-3797f45a8c12.png"> | <img width="374" alt="Screen Shot 2022-10-27 at 11 49 22 AM" src="https://user-images.githubusercontent.com/556051/198338625-03f30bed-47cd-4806-b2c5-fc66b748bb61.png">
> fix: ellipsize preview list content

- src/components/Messages/Preview.tsx
This PR makes the verified badge appear on the same line as the profile name in the message preview list.
Fixes #973
> fix: verified badge in preview

- data/feature-flags.ts
This PR adds a few new XMTP testers as well as a few duplicates for existing testers so we can test switching between multiple profiles.
> chore: allowlist more xmtp testers

- src/components/utils/hooks/useMessagePreviews.tsx
This PR fixes a small issue where the profile list wasn't refetching after changing profiles. It also makes it so we only re-route to /messages if there already was a selected profile.
https://user-images.githubusercontent.com/556051/198398584-48192701-49c3-49cc-81a3-793014f1db9a.mov
> fix: reload the conversation previews after changing profiles

- src/components/Layout.tsx
- src/components/Settings/Delete/index.tsx
Wipes keys from one of the locations recommended in https://github.com/lensterxyz/lenster/issues/912.
I'm not sure we need to wipe the keys in the other two locations. Our keys in localStorage are prefixed with both the environment and the wallet address, so if a user changes chains or changes wallets the old keys will not be used. In cases where the auth token is expired, we can keep the keys in storage and re-use them when the user logs back in. The client will be unset on any form of logout through [this line](https://github.com/lensterxyz/lenster/blob/clear-localstorage-on-all-logout-methods/src/components/utils/hooks/useXmtpClient.tsx#L61:L61)
Let me know what you think?
https://github.com/lensterxyz/lenster/issues/912.
> fix: clear LocalStorage on other logout mechanisms

- src/components/Messages/Composer.tsx
- src/components/Messages/Message.tsx
- When changing between conversations, the message composer box was being carried over. This fixes that to wipe the message composer box any time you change conversations.
- We may want to actually store this as state, so that the user can continue composing when they navigate back. I'm going to create a separate ticket for that and we can prioritize as necessary.
https://user-images.githubusercontent.com/65710/198716769-e865a5f8-78eb-4ffb-bfd9-c414024506b6.mp4
https://user-images.githubusercontent.com/65710/198716868-fcaa0757-21e5-4093-9094-ad0d36a798a3.mp4
> Wipe out message when changing conversations

- src/components/utils/hooks/useMessagePreviews.tsx
- When the `useMessagePreviews` hook is initially loaded, the `loading` state is set to false until the effects are run. These leads to a brief period where the state is not loading but there are no messages. This causes the UI to show the empty inbox state, when it in fact should be loading.
Fixes https://github.com/lensterxyz/lenster/issues/971
https://user-images.githubusercontent.com/65710/198720627-8a9c0909-696e-4859-ba29-e16f9a30d502.mp4
> fix: useMessagePreviews loading state

- src/components/Messages/MessagesList.tsx
- src/components/Messages/Preview.tsx
Fixes background in messages list and conversation preview hover state while in dark mode.
|Before|After|
|-|-|
|<img width="1242" alt="CleanShot 2022-10-29 at 18 14 18@2x" src="https://user-images.githubusercontent.com/510695/198858285-06146b5f-3ee2-497b-a5f2-c0a2b24beb47.png">|<img width="1261" alt="CleanShot 2022-10-29 at 18 14 02@2x" src="https://user-images.githubusercontent.com/510695/198858293-3355d248-9316-4ac1-a576-61ab6a3d735c.png">|
> fix: light mode styles in dark mode

- data/feature-flags.ts
- src/components/Home/EnableMessages.tsx
Updates Enable DMs panel with revised copy from XMTP.
> chore: update enable dm copy

- src/components/Messages/Preview.tsx
Disambiguates the message sender in the preview tile by prepending "You: " if the message was sent by the current user. This design pattern is used in Twitter DMs and Signal.
> feat: disambiguate sender in preview tile

- src/components/Profile/Feed.tsx
Updates empty state message to "Profile hasn't feeded yet" as opposed to "Profile doesn't feeded yet"
Fixes #1032  (issue)
Visit a profile with no posts and take a look at the feed tab.
> doc: empty feed typo fix

- src/components/Messages/MessagesList.tsx
- src/components/Shared/Markup.tsx
- src/styles.css
- Uses the `Markup` shared component to make URLs clickable in messages
- Does not apply the other markdown styles (let's leave that for another day)
Fixes #948
> feat: clickable links in messages

- src/components/Notification/Icon.tsx
- src/components/Shared/Navbar/index.tsx
Adds hover states for the notification and message icons in the top navigation bar using the current implementation for hover states on icons on desktop.
The current top navigation bar icons do not have a hover state on desktop.
Here is the current implementation of hover states on icon-only links/buttons:
Here's that same implementation added to the top navigation icons on desktop:
Notifications icon hovered:
Messages icon hovered:
Known issues:
- The notifications icon looks a bit odd when hovered with a badge but this would require a bit more planning to re-code/redesign how icons are treated on the app
> feat: adding hover states to top navigation icons

- src/components/Messages/Message.tsx
- Previously the page title would show `undefined • Lenster` while the page was still in a loading state. This updates the logic to only show the profile name/title once the profile has fully loaded.
https://user-images.githubusercontent.com/65710/199076560-a5e3c3dd-4abe-4c6e-83f0-bb664a455d2e.mp4
> fix: DM page title while loading

- src/components/utils/hooks/useGetMessages.tsx
- The "This is the beginning of the conversation" text would flicker when the page was loaded. This changes around the behaviour of the `hasMore` property so that it doesn't toggle between `true` and `false` while the first page is loading. 
https://user-images.githubusercontent.com/65710/199080609-30590d07-1405-4639-bcfb-4afc2273635c.mp4
> fix: remove "This is the beginning of the conversation" flicker

- src/components/Messages/Composer.tsx
When the "Send" button is disabled because the recipient has not enabled DMs, it should not have a hover state, because it cannot be activated.
> fix: hover state on disabled send button

- src/components/Notification/Icon.tsx
Fixes the movement in the nav icons on the badge show, hide
Fixes this jitter
https://user-images.githubusercontent.com/510695/198705860-25b1d211-038f-451d-a064-9757c0d5e362.gif
> fix: movement in nav icons on show badge true

- src/components/Messages/PreviewList.tsx
- src/components/Messages/index.tsx
- No longer redirects to the first conversation in the list
- Adds an empty state for the Messages page
https://user-images.githubusercontent.com/65710/199570760-daa660a6-01d9-4644-85d8-50f710e5a548.mp4
> revert: redirect to first conversation

- src/components/utils/hooks/useMessagePreviews.tsx
- src/lib/chunkArray.ts
- We realized the Lens API doesn't allow you to query for more than 50 profiles at a time, but also doesn't offer pagination when querying by `profileIds`. So, we are breaking the request into smaller chunks.
- Bonus is that when a new conversation is added it will only query for the one new profile instead of the whole batch
https://user-images.githubusercontent.com/65710/199830468-ee5fe5e7-8ad9-4cd4-a9cb-c05c1c269ecb.mp4
> fix: break up profiles into batches of 50

- src/components/utils/hooks/useXmtpClient.tsx
- src/constants.ts
Configures the XMTP client to include the app name and version in XMTP API headers.
> chore: add appVersion to xmtp client config

- src/components/Shared/Markup.tsx
- src/components/utils/matchers/UrlMatcher/index.tsx
Fixes #771
Details:
- Fixed ordering of matchers: URLMatcher now goes first to catch any URLs before the other matchers check for mention-tags, hashtags, etc.
- URLMatcher now marked as "void" (which means an URL cannot contain nested tags, see https://interweave.dev/docs/matchers/#creating-a-matcher )
- URLMatcher: when a blocked top-level-domain is found (i.e. ".lens"), set `response.valid = false;` This is the method in Interweave to filter out such false positives. (Before the fix, **null** was returned, which stopped the matcher from finding more matches, see https://interweave.dev/docs/matchers/#creating-a-matcher ) 
Before:
After:
Open  https://lenster.xyz/posts/0x24-0xc7 and check that URL is rendered correctly (whole URL clickable, and no mention-tag inside URL)
> fix: url matching

- src/components/utils/hooks/useMessagePreviews.tsx
There seems to be an issue loading the profiles in parallel, where it uses the same variables for each request. This works around that issue by loading them one at a time. Confirmed it works by lowering the number of concurrent profiles and testing in dev.
Will work on a subsequent fix that loads everything in parallel.
> fix: load profiles serially

- src/components/utils/matchers/HashtagMatcher.tsx
- Detect hashtags with digits, for example `#web3`,
- Detect hashtags with underscore, for example `#foo_bar`
- **Ignore** hashtags with only digits and/or underscore, for example `#123`, `#12_34`, `#_`)
Before fix:
After fix:
Here is a live example post which contains `#Web3` hashtag: https://lenster.xyz/posts/0x73a4-0x029e
- Create and view a post with the text. `#lens #web3 #foo_bar #123 #_ #12_34 #foo! #bar? #test. dfg`
- Verify that only `#lens`, `#web3`, `#foo_bar`, `#foo` and `#bar` are detected as hashtags.
> fix: hashtag matcher

- src/components/Publication/Actions/Collect/CollectModule.tsx
Pressing 'Shop Collects' button takes you to mirror's page instead of pointed page
Simple fix to move priority of publication.mirrorOf?.id in front of publication.id.
Without this, the button takes user's to the wrong page: the page of the mirror publication instead of the page of the publication being mirrored.
Fixes #1185 
Press Shop Collects button on a publication's mirror
> fix: Pressing 'Shop Collects' button takes you to mirror

- src/components/UI/LightBox.tsx
Fixes #1176
Fix the previous behavior which was that "Open original" opened both the original media and the corresponding post.
In the feed, find a post which has an image
Click the image. Image will show in full size, with a link "Open original"
Click "Open original"
Verify that the original is opened in a new tab, and that nothing happens in the original tab (should not open the post)
> fix: stop click propagation for open original (#1176)

- src/components/Profile/Feed.tsx
Fixes #1195
- Visit a profile that has empty feed/media/replies
- Check that the wording for the empty state under the feed tabs has correct grammar
**Before fix:**
**After fix:**
> fix: grammar in feed empty state

- apps/web/src/components/Shared/Markup.tsx
- apps/web/src/components/utils/matchers/markdown/MDCodeMatcher.tsx
Fixes #1236
The problem was that MDCodeMatcher was not marked as "void" (see https://interweave.dev/docs/matchers ) so it allowed sub-tags, which caused the crash. Also, the MDCodeMatcher need to be executed first, since a code snippet can contain any syntax, that could otherwise be caught by other matchers.
Visit https://lenster.xyz/posts/0x101e-0x07
Confirm that the page doesn't crash, but shows some code snippets with asterisk inside:
> fix: crash on some posts containing markdown code formatting

- README.md
the current readme.md license name wa error
change license MIT to GPLv3
> Change readme.md license MIT to GPLv3

- apps/web/src/lib/parseJwt.ts
What does this PR do?
This function is only provided for compatibility with legacy web platform APIs and should never be used in new code, because they use strings to represent binary data and predate the introduction of typed arrays in JavaScript. For code running using Node.js APIs, converting between base64-encoded strings and binary data should be performed using Buffer.from()
How should this be tested?
Check that the warning is gone in code scanning results
> feat: update atob api

- apps/web/src/lib/i18n.ts
Show dayjs strings (e.g. "5 days ago") in active language.
**Before:**
**After:**
Go to Settings > Account > Locale settings > Switch to a non-English language.
Go to notifications page and check the upper right timestamp. Timestamp should show translated to the active language.
> fix: dayjs localization

- apps/web/src/components/Shared/Login/WalletSelector.tsx
Avoid closing the login form when it should show "Claim your Lens profile".
[Screen recording](https://user-images.githubusercontent.com/667227/210209658-06a5fd1f-5bde-4184-9168-1b23e4542293.mp4)
Notes:
The three dialogs "Connect your wallet", "Please sign the message" and "Claim your Lens profile" use the same modal (apps/web/src/components/Shared/Login/index.tsx).
When the user tries to login with an address that has no account, the "Claim your Lens profile" should display. Therefor, in that scenario, the modal should not be closed.
Fixes #1497
In #1497, perform steps to reproduce and verify expected behavior
> fix: keep auth modal when no profile was found

- apps/web/src/components/Explore/index.tsx
Fixes #997
Save selected tab in http://localhost:4783/explore as a URL query parameter.
[Screen recording](https://user-images.githubusercontent.com/667227/210841401-fba1d09b-e59e-41c0-b8f2-df393b77b28b.mp4)
Note: Using `router.replace` so that the user can click around among the tabs without creating more browser history. If this is not the desired behavior, it can simply be changed to `router.push`.
> fix: persist tab in explore

- apps/web/src/components/Shared/Markup.tsx
- apps/web/src/components/utils/matchers/UrlMatcher/constants.ts
- apps/web/src/components/utils/matchers/UrlMatcher/index.tsx
Fixes #1599
After fix:
(purple color brightened for the screenshot to distinguish clearly from the black text)
See steps in #1599
> fix: url matcher for parentheses

- apps/web/src/components/Composer/Editor/index.tsx
New PR for #1193
As concluded in chat with @bigint :
> fix Lexical so that it only support newlines (similar to twitter)
After this PR, the Lexical editor will **only** create line breaks (\n), regardless of whether user presses _Shift+Enter_ or _Enter_.
(It will not create paragraphs (exported as \n\n), which it did before on _Enter_)
Write a post, try separating some lines with _Enter_ and some with _Shift+Enter_. Verify that in the resulting published post, the line breaks match how it looked in the editor.
> fix: create only line breaks in editor

- apps/web/src/components/Shared/Login/WalletSelector.tsx
Explicitly adds chainId to wagmi `useConnect` hook so that chainId is properly populated when instantiating a WalletConnectConnector.
Fixes #1668
> fix: set chainid to wagmi connectors

- apps/web/src/components/Comment/Feed.tsx
- apps/web/src/components/Comment/NoneRelevantFeed.tsx
- apps/web/src/components/Explore/Feed.tsx
- apps/web/src/components/Home/Highlights.tsx
- apps/web/src/components/Home/Timeline/index.tsx
- apps/web/src/components/Mod/Feed.tsx
- apps/web/src/components/NFT/NFTFeed.tsx
- apps/web/src/components/Notification/List.tsx
- apps/web/src/components/Profile/Feed.tsx
- apps/web/src/components/Profile/Followers.tsx
- apps/web/src/components/Profile/Following.tsx
- apps/web/src/components/Profile/MutualFollowers/List.tsx
- apps/web/src/components/Profile/NftGallery/Picker.tsx
- apps/web/src/components/Search/Profiles.tsx
- apps/web/src/components/Search/Publications.tsx
- apps/web/src/components/Shared/Modal/Collectors.tsx
- apps/web/src/components/Shared/Modal/Likes.tsx
- apps/web/src/components/Shared/Modal/Mirrors.tsx
> fix: remove unwanted hasMore state to prevent re-rendering

- apps/web/src/components/utils/hooks/useMessagePreviews.tsx
- apps/web/src/components/utils/hooks/useXmtpClient.tsx
- apps/web/src/store/conversation-cache.ts
- apps/web/src/store/message-cache.ts
Add conversation caching for DMs to drastically speed up conversation loading, especially for users with tons of conversations.
Close ENG-186
Load your messages page and confirm that loading of conversations is faster.
> feat: add conversation caching

- CONTRIBUTING.md
A simple fix for the broken link for running app locally
> Fix broken link for local development guide

- apps/web/src/components/Notification/FeedType.tsx
- apps/web/src/components/Notification/List.tsx
- apps/web/src/components/Notification/NotificationIcon.tsx
- apps/web/src/components/Shared/Navbar/BottomNavigation.tsx
Fixes #2172
New look:
Note: I think the bell icon in Heroicons V2 looks a bit better:
But then we would need to switch to V2, which would change all other icons too, so it may not be desired right now.
> fix: change bolt icon to bell icon for notification in navbar

- apps/web/src/components/Settings/Profile/NftPicture.tsx
- packages/lens/documents/queries/ProfileSettings.graphql
- packages/lens/generated.ts
The default chain ID for the form should be taken from the profile picture if it's been already configured. If not, we should fallback to Mainnet.
Currently, it always shows me Ethereum, even though my NFT avatar is on Polygon. And that's really confusing.
Unfortunately, there are no tests for the settings page. Hopefully, it's trivial enough to be accepted anyway.
> fix: let NftPicture set the correct chain ID

- packages/lib/getWalletDetails.ts
- tests/packages/lib/getWalletDetails.spec.ts
Updates name from `Wallet Connect` to `WalletConnect`
N/A
Changed title for WalletConnect modal. Changed name in test file too.
✌🏽
> Change Wallet Connect to WalletConnect

- apps/web/src/components/Messages/Preview.tsx
Fixes a regression in message preview text where we were showing `message.content` instead of the message content.
N/A
- Send a message that doesn't include an attachment
- Notice the message preview shows the content of that message
🩹
> fix: show message content for non-attachments

- apps/web/src/components/Messages/PreviewList.tsx
Updates the styling of the "Requests" tab to align with the styling of the other tabs. Also shows this tab in cases of 0 requests. 
Relates to the universal inbox changes from https://github.com/lensterxyz/lenster/pull/2866
Before (Requests is selected here, it just doesn't visually indicate that)
After 
🎨♻️🚚
> Update Requests styling

- apps/web/src/components/Shared/Oembed/Embed.tsx
Fixed embed truncate text issue
Line clamp CSS and truncate CSS don't work together 
🚀
> fix: embed truncate issue

- apps/web/src/components/Messages/Message.tsx
- apps/web/src/components/Messages/PreviewList.tsx
- apps/web/src/components/Messages/index.tsx
Height of two grids on dms screen was not same resolved it
Fixes #3033 
🚀
> fix: dms layout height issue

- apps/web/src/hooks/useMessagePreviews.tsx
Fixes ENS issue on DMS
Fixes #3728 
🚀
> fix: ens issue in dms

- .github/workflows/crowdin-download.yml
- .husky/pre-commit
It prevents commits that contain only blank lines.
Fixes # 3807
/claim #3807
- changed the pre-commit hook that checks if the staged changes only contain blank lines before committing the changes.
✅ ✅ ✅
> feat: prevent blankline commits

- apps/web/src/components/Staff/FeatureFlags/List.tsx
> Add killFeatureFlag function to List component

- apps/web/src/components/Shared/Navbar/BottomNavigation.tsx
A link to open profile when user is logged in on mobile view
https://github.com/heyxyz/hey/assets/65119631/f147e1e5-cf87-4f68-bdd0-dfae0aa81bc9
Fixes #4157
> feat: link to profile on bottom navbar

- apps/web/src/components/Staff/Sidebar.tsx
Unused Groups and Abuse removed from sidebar
Fixes #4273
> fix: group and abuse removed from sidebar

- apps/web/src/components/Home/PaidActions/OpenActionPaidAction.tsx
Reduced vertical padding on paid actions amount section
Fixes #4267
> fix: reduce padding-y on paid actions amount section

- apps/web/src/components/Publication/EncryptedPublication.tsx
Update the lock closed icon to `text-green-500` in encrypted post.
Fixes #4284
> chore: update lock icon color in encrypted post

- apps/web/src/components/Shared/Markup/MarkupLink/Hashtag.tsx
- apps/web/src/components/Shared/Navbar/NavItems/Logout.tsx
- fix: use ArrowRightStartOnRectangleIcon instead of ArrowRightOnRectangleIcon
- fix: hashtag search
> fix: hashtag search

- apps/web/src/components/Publication/EncryptedPublication/Criteria/ProfileOwnershipCondition copy.tsx
- apps/web/src/components/Publication/EncryptedPublication/Criteria/SecondTierCondition/index.tsx
- apps/web/src/components/Publication/EncryptedPublication/Criteria/ThirdTierCondition/index.tsx
- apps/web/src/components/Publication/EncryptedPublication/Criteria/index.tsx
> feat: add EoaOwnershipCondition check

- apps/og/src/app/layout.tsx
- apps/og/src/app/posts/[id]/page.tsx
- apps/og/src/app/u/[handle]/page.tsx
- apps/og/src/defaultMetadata.ts
> feat: add default og metadata

- .github/workflows/ci.yml
- apps/api/src/db/schema.prisma
- apps/api/src/routes/health.ts
- apps/api/src/utils/prisma.ts
- apps/api/tests/ens/index.spec.ts
- apps/api/tests/health.spec.ts
- packages/lib/getUniswapURL.spec.ts
> feat: add test coverage to: health

- apps/web/src/components/Publication/LensOpenActions/UnknownModule/Preview.tsx
- apps/web/src/components/Shared/Oembed/Embed.tsx
- apps/web/src/components/Shared/Sidebar/SidebarMenu.tsx
- apps/web/src/components/Shared/UserPreview.tsx
- package.json
- packages/ui/src/Alert.tsx
- packages/ui/src/Modal.tsx
- packages/ui/src/Tooltip.tsx
- pnpm-lock.yaml
- prettier.config.js
> fix: tailwind prettier errors

- .github/workflows/cron-db-cleanup.yml
- apps/api/src/routes/internal/cleanup/db.ts
> feat: add db cleanup cron

- apps/web/src/components/Home/Sidebar/HeyMembershipNft/Mint.tsx
- apps/web/src/components/Home/Sidebar/HeyMembershipNft/index.tsx
- apps/web/src/components/Publication/LensOpenActions/CollectModule/CollectAction.tsx
- apps/web/src/components/Publication/LensOpenActions/CollectModule/index.tsx
- apps/web/src/components/Publication/LensOpenActions/index.tsx
- apps/web/src/components/Settings/Allowance/Button.tsx
- apps/web/src/components/Shared/NoBalanceError/WrapWmatic.tsx
- apps/web/src/components/Shared/NoBalanceError/index.tsx
- apps/web/src/lib/fonts.ts
- apps/web/src/lib/getLivepeerTheme.ts
- apps/web/src/pages/500.tsx
- apps/web/src/pages/_app.tsx
> feat: add collect module for hey nft

- packages/ui/src/ErrorMessage.tsx
Fixes horizontal text overflow in the error message modal.
<details>
<summary>Before 👇</summary>
</details>
<details>
<summary>After 👇</summary>
</details>
Adds the tailwindcss class `break-words` to the error message text content to force mid-word breaks if necessary for cases where the text would otherwise horizontally overflow the modal.
> fix: error message text overflow

- apps/api/src/lib/oembed/meta/generateIframe.ts
- fic: console
- chore: kill figma and spline usage
> kill figma spline

- apps/web/src/lib/isFeatureAvailable.ts
- apps/web/src/lib/isFeatureEnabled.ts
- packages/data/constants.ts
> feat: add is_preview env check

- apps/web/src/components/Mod/FeedType.tsx
- apps/web/src/components/Mod/index.tsx
- apps/web/src/components/Staff/Users/List.tsx
- packages/data/constants.ts
- packages/data/enums.ts
> feat: add profiles tab to mod page

- apps/web/src/components/Shared/Auth/Signup/ChooseHandle.tsx
- packages/abis/HeyLensSignup.ts
- packages/contracts/.eslintrc.js
- packages/contracts/.gitignore
- packages/contracts/README.md
- packages/contracts/contracts/HeyLensSignup.sol
- packages/contracts/hardhat.config.ts
- packages/contracts/package.json
- packages/contracts/scripts/deploy.ts
- packages/contracts/tsconfig.json
- packages/data/contracts.ts
- pnpm-lock.yaml
> feat: hey lens signup contract

- apps/api/src/lib/sitemap/buildSitemap.ts
- apps/api/src/lib/sitemap/getLastModDate.ts
- apps/api/src/routes/sitemap/others.xml.ts
- apps/api/src/routes/sitemap/profiles/[id].xml.ts
- apps/api/src/routes/sitemap/publications/[id].xml.ts
- apps/web/package.json
- pnpm-lock.yaml
> chore: update deps

- apps/api/src/data/score-allocations.ts
- apps/api/src/routes/score/allocations.ts
- apps/web/src/components/Profile/Score.tsx
- apps/web/src/components/Shared/GlobalModals.tsx
- apps/web/src/components/Shared/Modal/Score.tsx
- apps/web/src/components/Shared/Navbar/NavItems/Score.tsx
- apps/web/src/store/non-persisted/useGlobalModalStateStore.ts
- packages/types/hey.d.ts
> feat: add allocations ui mvp

- apps/web/src/hooks/useActOnUnknownOpenAction.tsx
Makes the success toast stay longer
> fix: making success toast on Decent OA stay longer

- apps/web/src/components/Publication/OpenAction/UnknownModule/Decent/DecentAction.tsx
- apps/web/src/components/Publication/OpenAction/UnknownModule/Decent/FeedEmbed.tsx
- apps/web/src/components/Publication/OpenAction/UnknownModule/Decent/Module.tsx
- apps/web/src/components/Publication/OpenAction/UnknownModule/Decent/QuantityConfig.tsx
- Fixes the issues related to Decent OA publications on the Feed
- Fixes the management of active publications's modal on the feed
- Sets back quantity to 1 on modal close
- Fix the states, loadings, modals and data fetching on actionData changes, taking into account the NFTs that aren't available anymore (displaying an inactive embed for those)
> fix: decent feed issues

- apps/api/src/routes/frames/post.ts
- apps/web/src/components/Shared/Oembed/index.tsx
Frame POST must include `clientProtocol` for authenticated requests to specify protocol to verify Frame signature with.
> feat: add clientProtocol to Frame POST

- apps/api/src/helpers/oembed/meta/getFrame.ts
Allow Frames with no buttons. This is a common ending state, and is allowed in Open Frames spec and framesjs debugger.
Hey renders these Frames correctly already with this condition removed.
Example: https://stg-powered-by.percs.app/frames/aaa95153-6142-443f-9476-6d442bec9477/1
> feat: remove condition for frame buttons.length > 0

- apps/api/src/helpers/middlewares/validateLensAccount.ts
- apps/api/src/helpers/oembed/meta/getFrame.ts
- apps/api/src/routes/frames/post.ts
- apps/web/src/components/Shared/Oembed/Frames/index.tsx
- packages/types/misc.d.ts
Implements final piece of anonymous frame support. Only signs actions if frame explicitly contains `of:accepts:lens`.
Can be tested by using profile with Lens Manager disable and interacting with https://gm-frame-sable.vercel.app. Currently, this frame will return undefined (since data cannot be properly signed -> returns untrustedData incorrectly).
Closes #5066
> feat: anonymous frame spec support

- apps/web/src/components/Composer/Editor/Editor.tsx
There is a tiny API change in the latest version of ProseKit v0.9.13. A new option `defaultContent` is added and it deprecate the previous `defaultHTML` and `defaultDoc`.
~~Fixes # (issue)~~
> chore: migrate away from deprecated prosekit api

- apps/web/src/components/Home/Sidebar/index.tsx
- apps/web/src/components/Shared/Navbar/TopNavbar.tsx
- **feat: add profiles design**
- **chore: add fonts**
- **chore: comment out Navbar component in Layout.tsx for future review**
- **feat: refactor Home component to use MultiColumnLayout for improved layout management**
- **feat: move MultiColumnLayout to Shared component and update Home to use new layout structure**
- **feat: add TopNavbar component to Sidebar for improved navigation experience**
> feat: add TopNavbar component to Sidebar for improved navigation experience

- apps/web/src/helpers/profilePictureUtils.ts
- apps/web/src/hooks/useUploadAttachments.tsx
This pull request includes changes to the image compression settings in two different files to improve the handling of image uploads. The adjustments involve increasing the maximum file size and modifying the maximum width or height for compressed images.
Changes to image compression settings:
* [`apps/web/src/helpers/profilePictureUtils.ts`](diffhunk://#diff-f5b6e8f1b6d0c04f07c63494c14145e6eb17b8d6485c0f3dce8092796d67b073L35-R36): Increased `maxSizeMB` from 2 to 3 and decreased `maxWidthOrHeight` from 4096 to 2000 in the `uploadCroppedImage` function.
* [`apps/web/src/hooks/useUploadAttachments.tsx`](diffhunk://#diff-fe28f137d985355899f12321440395c6483572f779390caf8de7b188806a2cc7L64-R65): Increased `maxSizeMB` from 2 to 3 and increased `maxWidthOrHeight` from 4096 to 5000 in the …
> Don't compress images more while uploading

- apps/web/src/components/Shared/Navbar/Search/index.tsx
Fixes #5413
Remove the call to `reset` in the `handleKeyDown` function and update the `reset` function to no longer clear the search input.
* Remove the line `setSearchText("");` from the `reset` function.
* Remove the call to `reset` in the `handleKeyDown` function.
---
For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/heyxyz/hey/issues/5413?shareId=158d40cb-002f-480f-a5d5-0a048703e612).
> Fix search input reset on enter

- apps/web/src/components/Publication/ClubHandle.tsx
- apps/web/src/components/Publication/PublicationProfile.tsx
- apps/web/src/components/Publication/Source.tsx
This pull request includes several changes to improve the layout and styling of components in the `apps/web/src/components/Publication` directory. The changes primarily focus on removing unnecessary truncation and adjusting spacing for better visual consistency.
Styling improvements:
* [`apps/web/src/components/Publication/ClubHandle.tsx`](diffhunk://#diff-5403181ff579f9dc95e8b14d059088a0f549c27231c3410c22e527e2e5ed0b26L18-R19): Removed the `truncate` class from the `span` element and adjusted the margin class from `mx-1` to `mr-1` for better spacing.
* [`apps/web/src/components/Publication/PublicationProfile.tsx`](diffhunk://#diff-7df9e0acc22c3e1ef5cd6624b7063c11ee5df3e20821d97927aea6005471cea6L31-R31): Removed the `truncate` class from the `WrappedLink` component and adjusted the layout …
> Fix truncation of profile on big handles and names

- apps/web/package.json
- pnpm-lock.yaml
This pull request includes several dependency updates in the `apps/web/package.json` and `pnpm-lock.yaml` files. The changes primarily focus on updating versions of various packages to their latest releases.
Dependency updates:
* Updated `@unleash/proxy-client-react` to version `4.4.0` in `apps/web/package.json` and `pnpm-lock.yaml` [[1]](diffhunk://#diff-14b60f636e1a2b0061da57aaf231cb1ed15a5dc0c592425ed82e58fec95d42d8L35-R35) [[2]](diffhunk://#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bbL297-R298) [[3]](diffhunk://#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bbL4752-R4753) [[4]](diffhunk://#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bbL15781-R15777).
* Updated `@graphql-tools/delegate` to version `10.1.0` in …
> Update dependencies across all packages 📦

- .cursorrules
This pull request introduces extensive guidelines and best practices for coding, error handling, state management, and monorepo management. These changes aim to standardize the development process, improve code readability, and ensure robust error handling.
* **General Coding Practices**: Emphasizes writing correct, DRY, bug-free, and fully functional code. Encourages the use of early returns, descriptive naming, and accessibility features.
* **React and Styling**: Specifies the use of `export default` at the end of React files, TailwindCSS for styling, and arrow functions for event handlers.
* **Monorepo Best Practices**: Recommends using pnpm workspaces, ensuring proper package isolation, shared configurations, and scripts.
* **Error Handling**: Prioritizes handling errors and edge …
> Add Cursor rules for better suggestions

- apps/api/package.json
- apps/api/src/routes/oembed/helpers/getMetadata.ts
- apps/web/package.json
- apps/web/src/components/Composer/Actions/Gif/Categories.tsx
- apps/web/src/components/Composer/Actions/Gif/Gifs.tsx
- apps/web/src/helpers/authLink.ts
- apps/web/src/helpers/fetcher.ts
- apps/web/src/hooks/prosekit/useEmojis.tsx
- apps/web/vite.config.mjs
- packages/helpers/package.json
- packages/indexer/package.json
- pnpm-lock.yaml
This pull request removes the `axios` library and replaces its usage with the native `fetch` API across multiple files. Additionally, it cleans up the `pnpm-lock.yaml` file and several `package.json` files to reflect the removal of `axios`.
* [`apps/api/src/routes/oembed/helpers/getMetadata.ts`](diffhunk://#diff-94d6f8325c9dd2fed3a962bb97c64622f3466c563f23535080b1ad12c2f82670L1-R11): Replaced `axios` with `fetch` for fetching metadata.
* [`apps/web/src/components/Composer/Actions/Gif/Categories.tsx`](diffhunk://#diff-84639e6e421a4e9c9e2bf4491f34e0bd98f08fd66c33f2344485c973ffb3b645L5): Replaced `axios` with `fetch` for retrieving Giphy categories. [[1]](diffhunk://#diff-84639e6e421a4e9c9e2bf4491f34e0bd98f08fd66c33f2344485c973ffb3b645L5) …
> refactor: migrate to fetch from axios

- apps/web/src/components/Pages/Support.tsx
Hi! I found broken links in [support page](https://hey.xyz/support) - https://lens.xyz/legal/lens.xyz-privacy-policy.pdf
Fixed dead link - https://www.lens.xyz/privacy
> chore: fixed broken link in Support page

- apps/api/src/utils/lensPg.ts
Description:  
This pull request updates the method name from _initializeatDb to _initializeDb in the Database class within apps/api/src/utils/lensPg.ts. The change improves naming consistency and clarity throughout the codebase. No functional logic was altered; only the method name and its usage were updated.
> Refactor Database Initialization Method Naming for Consistency

- .github/workflows/ci.yml
Replaced deprecated `pnpm/action-setup@v2` with the latest `pnpm/setup-action@v4`.
This ensures compatibility with Node.js 20+ and removes deprecation warnings in CI.
> chore(ci): update pnpm action to latest version

- packages/data/utils/regexLookbehindAvailable.ts
Removes the redundant boolean type annotation in the immediately invoked function expression (IIFE) of regexLookbehindAvailable.ts. The type is already specified for the variable itself, making the function return type declaration unnecessary. This change improves code readability while maintaining the same functionality and type safety
>  Remove redundant type annotation in regexLookbehindAvailable IIFE
