heyverse/hey

src/apollo.ts
src/components/Post/index.tsx
src/components/Profile/index.tsx
src/components/Report/index.tsx
src/components/SiteLayout.tsx
src/components/utils/SEO.tsx
src/pages/posts/[id]/index.tsx
src/pages/u/[username]/index.tsx

Add meta tags to posts

---

src/components/Profile/Details.tsx
src/components/Profile/index.tsx

feat: add POH badge

---

src/components/Profile/Details.tsx

chore: add ens badge

---

src/components/Post/FullPost.tsx
src/components/Post/SinglePost.tsx
src/components/Post/Type/index.tsx
src/components/Post/index.tsx

feat: add entire pub clickable

---

src/components/Home/RecommendedProfiles.tsx
src/components/Post/RelevantPeople.tsx
src/components/Post/Shimmer.tsx
src/components/Post/index.tsx

feat: add relevant people to pub sidebar

---

src/components/Shared/Navbar/Search.tsx
src/components/Shared/Navbar/index.tsx

Rename `hideDrodown` prop to `hideDropDown` in Search component

fix(Search): rename prop

---

src/components/Post/Actions/index.tsx

Added role as `button` to div with `onClick`
Resolves [JS-0765](https://deepsource.io/gh/lensterxyz/lenster/issue/JS-0765/occurrences)

fix: add role attribute to div

---

cypress.config.ts
src/components/Shared/SelectCollectModule/FeeEntry.tsx

Added comments in empty functions.
Resolves [JS-0321](https://deepsource.io/gh/lensterxyz/lenster/issue/JS-0321/occurrences)

chore: add comments in no-op

---

src/pages/api/verified.ts

feat: add verified api

---

src/components/Shared/Navbar/Search.tsx
src/components/UI/Input.tsx

feat: add search icon to searchbar (#173)

---

src/components/Comment/NewComment/index.tsx
src/components/Community/Create.tsx
src/components/Community/Join.tsx
src/components/Crowdfund/Create.tsx
src/components/Post/Actions/Collect/CollectModule.tsx
src/components/Post/Actions/Mirror.tsx
src/components/Post/Crowdfund/Fund.tsx
src/components/Post/NewPost/index.tsx
src/components/Settings/Account/SetProfile.tsx
src/components/Settings/Account/SuperFollow.tsx
src/components/Settings/Delete/index.tsx
src/components/Settings/Profile/NFTPicture.tsx
src/components/Settings/Profile/Picture.tsx
src/components/Settings/Profile/Profile.tsx
src/components/Shared/Follow.tsx
src/components/Shared/SuperFollow/FollowModule.tsx

fix: use recklesslyUnprepared mode

---

src/components/Comment/NewComment/index.tsx
src/components/Community/Create.tsx
src/components/Crowdfund/Create.tsx
src/components/Post/Actions/Collect/CollectModule.tsx
src/components/Post/Crowdfund/Fund.tsx
src/components/Post/NewPost/index.tsx
src/components/Settings/Account/SetProfile.tsx
src/components/Settings/Account/SuperFollow.tsx
src/components/Settings/Profile/NFTPicture.tsx
src/components/Settings/Profile/Picture.tsx
src/components/Settings/Profile/Profile.tsx
src/lib/logger.ts

feat: add axiom logger

---

src/components/Shared/Uniswap.tsx
src/components/utils/Seo.tsx
src/constants.ts
src/fonts.css
src/styles.css

chore: use new assets url

---

src/components/Shared/Uniswap.tsx
src/components/utils/Seo.tsx
src/constants.ts
src/fonts.css
src/styles.css

Reverts lensterxyz/lenster#212

Revert "chore: use new assets url"

---

src/components/Comment/Feed.tsx
src/components/Explore/Feed.tsx
src/components/Home/Feed.tsx
src/components/Post/NewPost/Modal/index.tsx
src/components/Post/SinglePublication.tsx
src/components/Profile/Feed.tsx
src/components/Report/index.tsx
src/components/Search/Publications.tsx

chore: rename SinglePost component to SinglePublication

---

src/components/Post/FullPost.tsx
src/components/Post/PublicationBody.tsx
src/components/Post/SinglePublication.tsx
src/components/Post/ThreadBody.tsx

chore: rename PostBody component to PublicationBody

---

src/components/Publication/FullPublication.tsx
src/components/Publication/index.tsx

chore: rename FullPost component to FullPublication

---

src/components/Publication/FullPublication.tsx
src/components/Publication/HiddenPublication.tsx
src/components/Publication/SinglePublication.tsx
src/components/Publication/ThreadBody.tsx

chore: rename HiddenPost component to HiddenPublication

---

src/components/Publication/Type/CommunityPost.tsx
src/components/Publication/Type/index.tsx

chore: rename CommunityPost component to CommunityPublication

---

src/components/Publication/FullPublication.tsx
src/components/Publication/SinglePublication.tsx
src/components/Publication/Type/index.tsx

chore: rename PostType component to PublicationType

---

src/components/Publication/Shimmer.tsx
src/components/Publication/index.tsx

chore: rename PostPageShimmer component to PublicationPageShimmer

---

src/components/Comment/Feed.tsx
src/components/Comment/NewComment/index.tsx
src/components/Community/index.tsx
src/components/Notification/Type/CollectNotification/Amount.tsx
src/components/Notification/Type/CollectNotification/Content.tsx
src/components/Notification/Type/CollectNotification/index.tsx
src/components/Notification/Type/MirrorNotification.tsx
src/components/Publication/Actions/Collect/CollectModule.tsx
src/components/Publication/Actions/Collect/index.tsx
src/components/Publication/Actions/Comment.tsx
src/components/Publication/Actions/Like.tsx
src/components/Publication/Actions/Menu/Delete.tsx
src/components/Publication/Actions/Menu/Embed.tsx
src/components/Publication/Actions/Menu/Permalink.tsx
src/components/Publication/Actions/Menu/index.tsx
src/components/Publication/Actions/Mirror.tsx
src/components/Publication/Actions/index.tsx
src/components/Publication/FullPublication.tsx
src/components/Publication/NewPost/Modal/index.tsx
src/components/Publication/PublicationBody.tsx
src/components/Publication/SinglePublication.tsx
src/components/Publication/ThreadBody.tsx
src/components/Publication/Type/Collected.tsx
src/components/Publication/Type/Commented.tsx
src/components/Publication/Type/Mirrored.tsx
src/components/Publication/Type/index.tsx
src/components/Publication/index.tsx

chore: rename post props to publication

---

next.config.js
src/lib/logger.ts
src/pages/_app.tsx

chore: remove next-axiom

---

src/components/Comment/NewComment/index.tsx
src/components/Community/Details.tsx
src/components/Community/Settings/index.tsx
src/components/Explore/FeedType.tsx
src/components/Profile/FeedType.tsx
src/components/Publication/Crowdfund/index.tsx
src/components/Publication/NewPost/index.tsx
src/components/Shared/Navbar/MenuItems.tsx
src/components/Shared/SelectCollectModule/FeeEntry.tsx
src/components/Shared/SelectCollectModule/Modules.tsx
src/components/Shared/SelectCollectModule/index.tsx
src/components/Shared/SelectReferenceModule/index.tsx
src/tracking.ts

refactor: more mp events

---

src/components/Shared/Attachments.tsx
src/components/Shared/Markup.tsx

fix: click conflict

---

CONTRIBUTING.md
README.md
script/commands.txt

- **Be the change** - Don't wait for anything, if you want something ship it but make sure it is sustainable for the long term.
- **Pride in product** - We ask ourselves that will we use the feature if it's live before making it.
- **Diversity** - We welcome differences, and listen before we speak. It proportionally leads to extraordinary results and experiences.

docs: lenster values

---

script/commands.txt
src/components/Comment/Feed.tsx
src/components/Explore/Feed.tsx
src/components/Home/Feed.tsx
src/components/Notification/List.tsx
src/components/Profile/Feed.tsx
src/components/Profile/Followers.tsx
src/components/Profile/Following.tsx
src/components/Profile/NFTFeed.tsx
src/components/Search/Profiles.tsx
src/components/Search/Publications.tsx
src/components/Shared/Collectors.tsx
src/tracking.ts

chore: add paginate tracking

---

data/apps.ts

feat: add lenstube bytes

---

src/components/Comment/NewComment/index.tsx
src/components/Publication/NewPost/index.tsx
src/components/UI/MentionTextArea.tsx
src/store/publication.ts

feat: use global state for publication contents

---

src/components/Publication/NewPost/Modal/index.tsx

feat: add new post from support

---

data/hashflags.ts
src/components/Publication/NewPost/Modal/index.tsx

feat: support hashtags

---

src/components/Comment/NewComment/index.tsx
src/components/Publication/NewPost/Modal/index.tsx
src/components/Publication/NewPost/index.tsx
src/components/Shared/Preview.tsx
src/store/publication.ts

feat: add preview state and add it to intent

---

src/components/Publication/Actions/Collect/index.tsx
src/components/Publication/Actions/Comment.tsx
src/components/Publication/Actions/Like.tsx
src/components/Publication/Actions/Menu/index.tsx
src/components/Publication/Actions/Mirror.tsx

fix: action icon size in mweb

---

.eslintrc

chore: add `react/self-closing-comp` rule

---

.gitignore
src/components/Home/Hero.tsx
src/lib/mixpanel.ts
src/styles.css

- fix mixpanel startup issue
- add .idea folder to .gitignore

feat: Add darkmode support for hero section

---

src/components/Settings/Delete/index.tsx

feat: add alert prompt before deleting the account

---

package.json
src/components/Comment/NewComment/index.tsx
src/components/Community/Create.tsx
src/components/Community/Join.tsx
src/components/Crowdfund/Create.tsx
src/components/Publication/Actions/Collect/CollectModule.tsx
src/components/Publication/Actions/Mirror.tsx
src/components/Publication/Crowdfund/Fund.tsx
src/components/Publication/NewPost/index.tsx
src/components/Settings/Account/SetProfile.tsx
src/components/Settings/Account/SuperFollow.tsx
src/components/Settings/Delete/index.tsx
src/components/Settings/Profile/NFTPicture.tsx
src/components/Settings/Profile/Picture.tsx
src/components/Settings/Profile/Profile.tsx
src/components/Shared/Follow.tsx
src/components/Shared/SuperFollow/FollowModule.tsx
src/components/Shared/Unfollow.tsx
tailwind.config.js

chore: add mp track for signed data error

---

src/components/Profile/Details.tsx
src/components/Publication/index.tsx
src/components/StaffTools/MetaDetails.tsx
src/components/StaffTools/Profile.tsx
src/components/StaffTools/Publication.tsx

feat: add post staff tool

---

.github/PULL_REQUEST_TEMPLATE.md
src/components/Home/ProfileWarning.tsx
src/components/Settings/Account/Verification.tsx
src/components/Shared/Uniswap.tsx

chore: update verified section copy

---

src/components/Community/Details.tsx
src/components/Profile/Details.tsx

fix: community avatar

---

src/components/Publication/RelevantPeople.tsx

fix: regex for relevant folks sanitizer

---

.vscode/tasks.json
package-lock.json

feat: add vscode task

---

src/apollo.ts
src/components/Shared/Attachment.tsx
src/components/Shared/Attachments.tsx
src/components/Shared/IFramely/index.tsx
src/constants.ts
src/lib/formatAddress.ts

fix: remove unwanted else and add attachments type check

---

.vscode/tasks.json
src/lib/uploadToArweave.ts
src/pages/api/upload.ts

fix|refactor: arweave upload

---

src/components/Publication/Crowdfund/index.tsx
src/components/Publication/Type/Collected.tsx
src/components/Publication/Type/Mirrored.tsx
src/components/Publication/Type/index.tsx
src/components/UI/Card.tsx
src/graphql/CommentFields.ts

fix: show name and add event stop for crowdfund

---

.github/PULL_REQUEST_TEMPLATE.md
src/components/Profile/Feed.tsx
src/components/Profile/NFTFeed.tsx

fix: copy grammar in profile page in empty state

---

src/components/Publication/Actions/Mirror.tsx
src/graphql/MirrorFields.ts

fix: has mirrored from mirrored publications

---

src/components/Publication/Actions/Collect/index.tsx
src/graphql/CommentFields.ts
src/graphql/MirrorFields.ts
src/graphql/PostFields.ts

feat: show has collected

---

src/components/Publication/Actions/Collect/CollectModule.tsx
src/components/Publication/Actions/Like.tsx
src/components/Publication/Actions/Menu/Embed.tsx
src/components/Publication/Actions/Menu/Permalink.tsx
src/components/Publication/Actions/Mirror.tsx
src/components/Publication/Crowdfund/index.tsx
src/components/Publication/SinglePublication.tsx
src/components/Publication/ThreadBody.tsx
src/components/Publication/Type/CommentedPublication.tsx
src/components/Publication/Type/CommunityPost.tsx
src/generated/lenstertypes.ts
src/graphql/CommentFields.ts

fix: remove unwanted pubId

---

src/components/Home/RecommendedProfiles.tsx
src/components/Notification/List.tsx
src/components/Profile/Followers.tsx
src/components/Profile/Following.tsx
src/components/Publication/PublicationBody.tsx
src/components/Publication/RelevantPeople.tsx
src/components/Search/Profiles.tsx
src/components/Shared/Collectors.tsx
src/components/Shared/CommunityProfile.tsx
src/components/Shared/Navbar/Search.tsx
src/components/SiteLayout.tsx
src/graphql/CommentFields.ts
src/graphql/MirrorFields.ts
src/graphql/PostFields.ts
src/graphql/ProfileFields.ts

fix: use fragments :tada:

---

src/components/Comment/New.tsx
src/components/Home/EnableDispatcher.tsx
src/components/Publication/New/index.tsx
src/components/Settings/Dispatcher/ToggleDispatcher.tsx
src/components/Settings/Dispatcher/index.tsx
src/components/Settings/Profile/Profile.tsx
src/components/Shared/Navbar/Login/WalletSelector.tsx
src/components/Shared/Navbar/MenuItems.tsx
src/components/SiteLayout.tsx
src/store/app.ts

fix: remove extra canUseRelay state

---

src/components/Publication/PublicationBody.tsx
src/components/Shared/IFramely/index.tsx

refactor: iframely

---

package-lock.json
package.json
src/components/Comment/New.tsx
src/components/Community/Join.tsx
src/components/Community/New.tsx
src/components/Crowdfund/New.tsx
src/components/Publication/Actions/Collect/CollectModule.tsx
src/components/Publication/Actions/Mirror.tsx
src/components/Publication/Crowdfund/Fund.tsx
src/components/Publication/New/index.tsx
src/components/Settings/Account/SetProfile.tsx
src/components/Settings/Account/SuperFollow.tsx
src/components/Settings/Delete/index.tsx
src/components/Settings/Dispatcher/ToggleDispatcher.tsx
src/components/Settings/Profile/NFTPicture.tsx
src/components/Settings/Profile/Picture.tsx
src/components/Settings/Profile/Profile.tsx
src/components/Shared/Follow.tsx
src/components/Shared/SuperFollow/FollowModule.tsx
src/components/Shared/Unfollow.tsx
src/lib/getSignature.ts

feat: add getSignature util

---

src/components/Layout.tsx
src/pages/Providers.tsx
src/pages/_app.tsx

chore: reduce bundle size

---

.github/workflows/analyze.yml
.github/workflows/ci.yml
next.config.js
package.json

feat: add next bundle analyzer

---

.github/workflows/analyze.yml
.github/workflows/analyze_comment.yml
.github/workflows/ci.yml

chore: use actions/cache@v3

---

README.md

doc: add utils to supporting repos

---

.eslintrc
package.json
src/components/Layout.tsx
src/components/Publication/RelevantPeople.tsx
src/components/Publication/ViaApp.tsx
src/components/Publication/index.tsx
src/components/Settings/Delete/index.tsx
src/components/Shared/Attachment.tsx
src/components/Shared/Navbar/SignedUser.tsx
src/components/utils/matchers/MentionMatcher.tsx
src/components/utils/matchers/markdown/MDQuoteMatcher.tsx
src/constants.ts
src/lib/getURLs.ts
src/lib/nFormatter.ts
src/lib/uploadToArweave.ts
src/pages/api/ping.ts
src/pages/api/upload.ts
src/pages/api/verified.ts
src/store/app.ts
yarn.lock

fix: add eslint plugin unicorn

---

src/components/Report/Reason.tsx
src/components/Report/index.tsx

feat: add spam reason and pub card

---

src/components/Publication/Actions/Collect/CollectModule.tsx

feat: add createCollectProxyAction

---

src/components/Home/RecommendedProfiles.tsx

chore: fix who to follow comp cache

---

src/apollo.ts
src/components/Comment/Feed.tsx
src/components/Explore/Feed.tsx
src/components/Home/Feed.tsx
src/components/Notification/List.tsx
src/components/Profile/Feed.tsx
src/components/Profile/Followers.tsx
src/components/Profile/Following.tsx
src/components/Profile/NFTFeed.tsx
src/components/Search/Profiles.tsx
src/components/Search/Publications.tsx
src/components/Shared/Collectors.tsx
src/generated/types.ts
src/lib/cursorBasedPagination.ts

feat: add apollo cache

---

src/components/Comment/New.tsx
src/components/Community/Join.tsx
src/components/Community/New.tsx
src/components/Community/Settings/index.tsx
src/components/Crowdfund/New.tsx
src/components/Home/RecommendedProfiles.tsx
src/components/Publication/Actions/Collect/CollectModule.tsx
src/components/Publication/Actions/Like.tsx
src/components/Publication/Actions/Menu/Delete.tsx
src/components/Publication/Actions/Mirror.tsx
src/components/Publication/Crowdfund/Fund.tsx
src/components/Publication/New/index.tsx
src/components/Report/index.tsx
src/components/Settings/Account/SetProfile.tsx
src/components/Settings/Account/SuperFollow.tsx
src/components/Settings/Allowance/Button.tsx
src/components/Settings/Delete/index.tsx
src/components/Settings/Dispatcher/ToggleDispatcher.tsx
src/components/Settings/Profile/NFTPicture.tsx
src/components/Settings/Profile/Picture.tsx
src/components/Settings/Profile/Profile.tsx
src/components/Shared/Follow.tsx
src/components/Shared/Navbar/Login/WalletSelector.tsx
src/components/Shared/SuperFollow/FollowModule.tsx
src/components/Shared/Unfollow.tsx
src/components/utils/hooks/useBroadcast.tsx
src/lib/mixpanel.ts
src/lib/onError.ts

refactor: onCompleted and onError

---

src/components/Crowdfund/New.tsx
src/components/Notification/Type/CollectNotification/Content.tsx
src/components/Profile/Cover.tsx
src/components/Publication/Crowdfund/index.tsx
src/components/Settings/Profile/Profile.tsx
src/components/UI/MentionTextArea.tsx

fix: use getIPFSLink everywhere

---

src/components/Comment/New.tsx
src/components/Community/Join.tsx
src/components/Community/New.tsx
src/components/Community/Settings/index.tsx
src/components/Crowdfund/New.tsx
src/components/Publication/Actions/Collect/CollectModule.tsx
src/components/Publication/Actions/Like.tsx
src/components/Publication/Actions/Menu/Delete.tsx
src/components/Publication/Actions/Mirror.tsx
src/components/Publication/Crowdfund/Fund.tsx
src/components/Publication/New/index.tsx
src/components/Settings/Account/SetProfile.tsx
src/components/Settings/Account/SuperFollow.tsx
src/components/Settings/Delete/index.tsx
src/components/Settings/Dispatcher/ToggleDispatcher.tsx
src/components/Settings/Profile/NFTPicture.tsx
src/components/Settings/Profile/Picture.tsx
src/components/Settings/Profile/Profile.tsx
src/components/Shared/Follow.tsx
src/components/Shared/SuperFollow/FollowModule.tsx
src/components/Shared/Unfollow.tsx

chore: use <Mutation> type in useMutation

---

src/components/Layout.tsx

fix: auth blink

---

src/components/Publication/Actions/Collect/CollectModule.tsx

fix: hide collect button if hasCollectedByMe

---

data/hashflags.ts
src/components/Publication/Type/CommunityPost.tsx
src/components/Settings/Allowance/Allowance.tsx
src/components/Shared/IFramely/Embed.tsx
src/components/Shared/IFramely/Player.tsx
src/generated/lenstertypes.ts

chore: reduce usage of  `any`

---

src/apollo/index.ts
src/components/Publication/Actions/Collect/index.tsx
src/components/Publication/Actions/Comment.tsx
src/components/Publication/Actions/Like.tsx
src/components/Publication/Actions/Menu/index.tsx
src/components/Publication/Actions/Mirror.tsx
src/components/Publication/Actions/index.tsx
src/components/Publication/FullPublication.tsx
src/components/Publication/PublicationStats.tsx
src/components/Shared/Likes.tsx
src/components/Shared/Mirrors.tsx
src/tracking.ts

feat: redesign single publication page

---

src/components/Profile/Feed.tsx
src/components/Profile/FeedType.tsx
src/components/Profile/index.tsx

feat: merge posts + mirrors in profile and call it feed and rename comments to replies

---

src/apollo/index.ts
src/components/Profile/Details.tsx
src/components/Profile/MutualFollowers/List.tsx
src/components/Profile/MutualFollowers/index.tsx
src/tracking.ts

feat: add mutual followers

---

src/components/Profile/MutualFollowers/index.tsx

fix: mutual followers

---

src/components/Profile/Feed.tsx
src/components/Profile/FeedType.tsx
src/components/Profile/index.tsx

feat: add media section in profile

---

src/components/Comment/New.tsx
src/components/Community/Join.tsx
src/components/Community/New.tsx
src/components/Crowdfund/New.tsx
src/components/Home/index.tsx
src/components/Layout.tsx
src/components/Notification/index.tsx
src/components/Publication/Actions/Like.tsx
src/components/Publication/Actions/Mirror.tsx
src/components/Publication/New/index.tsx
src/components/Settings/Account/SetProfile.tsx
src/components/Settings/Account/SuperFollow.tsx
src/components/Settings/Delete/index.tsx
src/components/Settings/Profile/NFTPicture.tsx
src/components/Settings/Profile/Picture.tsx
src/components/Settings/Profile/Profile.tsx
src/components/Shared/Navbar/Login/WalletSelector.tsx
src/components/Shared/Navbar/SignedUser.tsx
src/components/Shared/Navbar/index.tsx
src/components/Shared/SuperFollow/FollowModule.tsx
src/components/Shared/Unfollow.tsx
src/store/app.ts

fix: remove unused isAuthenticated state

---

src/components/Shared/ReferenceAlert.tsx

fix: followers can collect copy in collect modal

---

README.md

Fixed a comma to make it sound more direct

chore: fix comma in README.md

---

src/components/Explore/index.tsx
src/components/Home/Feed.tsx
src/components/Home/index.tsx
src/components/Profile/index.tsx
src/components/Publication/index.tsx
src/components/Shared/Navbar/index.tsx

chore: remove lazy loads

---

CONTRIBUTING.md

A few text improvements, typo fixes

doc: update CONTRIBUTING.md, text improvements and typos

---

src/components/Publication/Actions/Like.tsx

chore: add apollo state update for likes

---

src/components/Publication/Actions/Mirror.tsx
src/components/utils/hooks/useBroadcast.tsx

chore: add apollo state cache modify for mirrors

---

src/constants.ts

fix: RELAY_ON check

---

src/components/Shared/Navbar/Login/index.tsx

Replace an http link with https.

fix: use https link to prevent MITM attacks

---

src/components/Layout.tsx
src/components/Settings/Delete/index.tsx
src/components/Shared/Navbar/Login/WalletSelector.tsx
src/components/Shared/Navbar/SignedUser.tsx
src/store/app.ts

chore: remove isAuthenticated state

---

src/constants.ts

Changes the Regex validation for profile editing the website field.
(Because it is a few character change)
(I hope it doesnt lol)
(edited through github gui so dont know)
(... cuz is small)
(cuz github ui)

Update TLD Regex Max Length

---

package.json
src/apollo.ts
src/components/Layout.tsx
src/components/Settings/Delete/index.tsx
src/components/Shared/Navbar/Login/WalletSelector.tsx
src/components/Shared/Navbar/SignedUser.tsx
src/lib/getIsAuthTokensAvailable.ts
src/lib/resetAuthData.ts
yarn.lock

fix: refactor auth

---

src/apollo.ts

fix: call refresh api in async way

---

src/components/Crowdfund/New.tsx
src/components/Publication/SinglePublication.tsx
src/components/Publication/ThreadBody.tsx

fix: crowdfund creation issue

---

src/components/Notification/WalletProfile.tsx
src/components/Shared/Navbar/Login/New/index.tsx
src/components/Shared/WalletProfile.tsx
src/components/UI/MentionTextArea.tsx
src/lib/getAvatar.ts
src/lib/getStampFyiURL.ts

feat: add getStampFyiURL util

---

data/verified.ts

Add arnau ramio to verified

---

src/lib/uploadMediaToIPFS.ts

fix(temp): update estuary endpoint

---

src/components/Notification/List.tsx
src/constants.ts
src/lib/cursorBasedPagination.ts

Found another bug that was affecting some queries (for .e.g notification count and notification list).
Have a look at TODO as it's something we also need to fix as it's potentially some yet uknown behaviour related to notificatioins count.

fix: cursor based pagination helper

---

.github/workflows/lint.yml

Adds a Github action that lints, typechecks, and checks formatting. We want to ensure we keep the repo clean if we can.

chore: add lint github action

---

src/components/Composer/Post/New.tsx
src/components/Composer/Post/Update/index.tsx
src/components/UI/MentionTextArea.tsx
src/styles.css

chore: update new post modal

---

src/components/Composer/Comment/New.tsx
src/components/Composer/Post/Update/index.tsx
src/components/Shared/SelectReferenceModule/index.tsx
src/store/referencemodule.ts
src/tracking.ts

refactor: who can comment and mirror

---

package.json
src/components/Home/Feed.tsx
src/components/Publication/SinglePublication.tsx
src/styles.css
yarn.lock

Reverts lensterxyz/lenster#815

Revert "feat: add virtual list"

---

src/lib/uploadMediaToIPFS.ts

Reverts lensterxyz/lenster#823
cc @shanpriyan

Revert "chore: Unexpected `await` inside a loop"

---

src/components/Shared/Attachment.tsx
src/lib/uploadMediaToIPFS.ts

@shanpriyan fixed here by converting filelist to js array

fix: upload multiple files at ones

---

data/feature-flags.ts

Adds Peter (XMTP head of Growth) and Shane (XMTP Cofounder) to the feature flag so that they can track progress.
N/A

chore: add XMTP team members to feature flag

---

src/lib/uploadMediaToIPFS.ts

fix: using infura as backup

---

data/feature-flags.ts

Add 4 more XMTP employees to the messages allowlist.

chore: add jazz, akhil, j-ha & matt to messages

---

data/feature-flags.ts

Adds the Aave team to the feature flag so that they can start playing with messaging early.

Add aave members to ff

---

src/components/Messages/MessagesList.tsx
src/components/Messages/index.tsx

Use boolean attributes notation for JSX
Fixes #890

chore: prefer boolean attributes notation for JSX

---

src/components/Shared/Audio/CoverImage.tsx
src/components/Shared/Audio/index.tsx

fix:  handle mobile view in audio player

---

src/components/Composer/Comment/New.tsx
src/components/Composer/Post/Update/index.tsx

fix: audio metadata

---

src/lib/imageProxy.ts

chore: use buffer for imageproxy helper

---

src/components/Shared/Unfollow.tsx

feat: gasless unfollow

---

src/components/Shared/Attachment.tsx

chore: remove multiple from audio, video picker

---

package.json
src/components/Messages/MessagesList.tsx
src/components/Messages/Preview.tsx
src/components/utils/hooks/useMessagePreviews.tsx
src/components/utils/hooks/useStreamMessages.tsx
src/lib/getUniqueMessages.ts
src/store/message.ts
yarn.lock

- Upgrades `xmtp-js` to the latest version of the SDK, which introduces a new `DecodedMessage` type returned from all messaging functions

Upgrade to latest beta

---

src/components/Composer/Comment/New.tsx
src/components/Composer/Post/Update/index.tsx
src/components/Publication/Actions/Mirror.tsx
src/components/Settings/Profile/NFTPicture.tsx
src/components/Settings/Profile/Picture.tsx
src/components/Settings/Profile/Profile.tsx

feat: add fallback to proxyaction

---

src/components/Home/Timeline/EventType/Combined.tsx
src/components/Home/Timeline/EventType/Liked.tsx
src/components/Home/Timeline/EventType/ProfileCircles.tsx
src/components/Home/Timeline/EventType/index.tsx

feat: improve combined reactions label

---

data/verified.ts

chore: update verified.ts

---

src/components/Home/Timeline/index.tsx
src/lib/resetAuthData.ts
src/store/timeline.ts

chore: set reactions to false by default

---

src/components/Home/FeedEventFilters.tsx
src/components/Home/Timeline/index.tsx
src/store/timeline.ts

chore: remove reactions

---

src/components/Profile/Details.tsx
src/components/Shared/Slug.tsx
src/components/utils/matchers/MentionMatcher.tsx

fix: slug font size mismatch

---

src/components/Messages/Message.tsx
src/components/Messages/Preview.tsx
src/components/Messages/PreviewList.tsx

- Gives the selected conversation a purple background
https://user-images.githubusercontent.com/65710/198902009-8e09b873-e0bd-4172-80b9-74b00cc8f53d.mp4

feat: selected preview item background color

---

src/components/Notification/NotificationIcon.tsx

fix: notification dot

---

src/components/Messages/MessagesList.tsx

chore: message overflow issue fixed

---

src/styles.css

Fixes #1068 
https://www.loom.com/share/91ed65f0b80845f48c25a760046c09d4

fix: change hover link styling to same as twitter

---

src/components/Messages/Composer.tsx
src/components/Messages/MessageHeader.tsx
src/components/Messages/MessageIcon.tsx
src/components/Messages/Preview.tsx
src/components/Messages/PreviewList.tsx

Some classnames and tags cleanup
cc @bhavya2611 @elisealix22

chore: refactor DM codebase

---

package.json
yarn.lock

- Upgrades xmtp-js to the newly released 7.0.0, instead of the beta release we were using before

deps: use non-beta xmtp-js release

---

src/components/Home/Timeline/EventType/Commented.tsx
src/components/Publication/SinglePublication.tsx

Reverts lensterxyz/lenster#1034

Revert "feat: show post thread with OG post"

---

src/components/Messages/MessagesList.tsx
src/components/Messages/Preview.tsx
src/components/Messages/PreviewList.tsx
src/components/Profile/Following.tsx

fix: chat page in dark mode

---

src/components/Messages/PreviewList.tsx

fix: error message in preview list

---

data/verified.ts

chore: update verified list

---

src/components/Composer/Comment/New.tsx
src/components/Composer/Post/Update/index.tsx
src/lib/getTextNftSvg.ts
src/lib/getTextNftUrl.ts
src/lib/uploadToIPFS.ts

https://testnets.opensea.io/assets/mumbai/0xda2a3e26b89c562bdf80778603efff36119e1d99/1

feat: nft imge for text pubs

---

src/components/Composer/Comment/New.tsx
src/components/Composer/Post/Update/index.tsx

fix: add ipfs nft upload after loading

---

src/components/Profile/MutualFollowers/index.tsx
src/components/Shared/UserPreview.tsx

chore: handle mobile view profile preview

---

src/components/Notification/Type/CollectNotification/index.tsx
src/components/Notification/Type/CommentNotification.tsx
src/components/Notification/Type/FollowerNotification.tsx
src/components/Notification/Type/LikeNotification.tsx
src/components/Notification/Type/MentionNotification.tsx
src/components/Notification/Type/MirrorNotification.tsx
src/components/Shared/UserPreview.tsx
src/components/Shared/UserProfile.tsx

feat: add profile preview to notifications

---

src/components/Settings/Profile/Profile.tsx

chore: make website optional

---

src/components/utils/matchers/HashtagMatcher.tsx

chore: remove console

---

data/aave-members.ts

Adds bensparks.lens to Aave members list.

chore: update aave members list

---

src/apollo.ts
src/components/Profile/Feed.tsx
src/components/Profile/FeedType.tsx
src/components/Profile/Filters/MediaFilter.tsx
src/store/profile-feed.ts

feat: add filter to profile feed media

---

src/components/Publication/Actions/Collect/CollectModule.tsx

deprecate the shop collects button, as it's not performing well 🙇🏼

deprecate: shop collects button

---

package.json
src/components/Comment/Feed.tsx
src/components/Explore/Feed.tsx
src/components/Home/Highlights.tsx
src/components/Home/Timeline/index.tsx
src/components/Mod/Feed.tsx
src/components/Profile/Feed.tsx
src/components/Publication/QueuedPublication.tsx
src/components/Publication/SinglePublication.tsx
src/components/Search/Publications.tsx
src/components/Shared/Shimmer/PublicationsShimmer.tsx
src/styles.css
yarn.lock

Reverts lensterxyz/lenster#1221

Revert "feat: add virtual list for timelines"

---

src/components/Profile/MutualFollowers/index.tsx
src/lib/getIPFSLink.ts
src/lib/getThumbnailUrl.ts

fix: profile crash

---

packages/data/verified.ts

Verifies memester-xyz.lens, and associated team founders

chore: verify memester & founders

---

apps/web/src/lib/leafwatch.ts
apps/web/src/pages/_app.tsx
apps/web/src/pages/_document.tsx

Reverts lensterxyz/lenster#1301

Revert "chore: move to umami"

---

apps/web/src/components/Comment/Feed.tsx
apps/web/src/components/Explore/Feed.tsx
apps/web/src/components/Home/Highlights.tsx
apps/web/src/components/Home/SeeThroughLens.tsx
apps/web/src/components/Home/Timeline/index.tsx
apps/web/src/components/Messages/MessagesList.tsx
apps/web/src/components/Mod/Feed.tsx
apps/web/src/components/Notification/List.tsx
apps/web/src/components/Profile/Feed.tsx
apps/web/src/components/Publication/RelevantPeople.tsx
apps/web/src/components/Search/Profiles.tsx
apps/web/src/components/Search/Publications.tsx
apps/web/src/components/Settings/Profile/NFTPicture.tsx
apps/web/src/components/Settings/Profile/index.tsx
apps/web/src/components/Shared/Lexical/Plugins/AtMentionsPlugin.tsx
apps/web/src/components/Shared/Navbar/Search.tsx
apps/web/src/components/Shared/Navbar/SignedUser.tsx
apps/web/src/components/utils/hooks/useMessagePreviews.tsx
apps/web/src/lib/getTags.ts
apps/web/src/lib/leafwatch.ts

chore: remove all ts-ignores

---

apps/web/src/components/Shared/Lexical/Plugins/AtMentionsPlugin.tsx
apps/web/src/components/Shared/Lexical/Plugins/ToolbarPlugin.tsx

improve UI of mention dropdown and editor border for dark mode

chore: fix ui of mentions and border in editor for dark mode

---

apps/web/src/components/Shared/Attachments.tsx
apps/web/src/lib/uploadToIPFS.ts
packages/data/constants.ts

Fixes # ([issue](https://github.com/lensterxyz/lenster/issues/1341))
https://www.loom.com/share/aebdcbd7b0be4567837a803d074d610a

fix: image duplicated when multiple upload

---

apps/web/src/components/Shared/Footer.tsx
apps/web/src/tracking.ts

Reverts lensterxyz/lenster#1347

Revert "chore: add analytics to footer"

---

packages/data/aave-members.ts

chore: update aave-members.ts

---

apps/web/src/lib/formatHandle.ts

fix: case insensitive checking 

---

apps/web/src/lib/cursorBasedPagination.ts

Fixes # ([issue  #1031](https://github.com/lensterxyz/lenster/issues/1031))
Fixes # ([issue  #1364](https://github.com/lensterxyz/lenster/issues/1364))

fix: duplicate posts and profiles

---

apps/web/src/components/Explore/FeedType.tsx
apps/web/src/components/Home/RecommendedProfiles.tsx
apps/web/src/components/Publication/SinglePublication.tsx
apps/web/src/components/Shared/Navbar/SignedUser.tsx
apps/web/src/components/Shared/Navbar/index.tsx
apps/web/src/components/UI/Card.tsx
apps/web/src/components/UI/Input.tsx
apps/web/src/components/UI/Modal.tsx
apps/web/src/components/UI/TextArea.tsx

Makes dark mode darker. See attached screen recording.
https://user-images.githubusercontent.com/667227/208075665-e3a731ed-cd41-4b13-9b52-03460bf309c1.mp4
(mainly changed grey-900 to black, and grey-800 to gray-900)
Fixes #776

fix: make dark mode darker

---

apps/web/src/components/Shared/Attachments.tsx
apps/web/src/components/Shared/Video.tsx

feat: set video poster

---

apps/web/src/components/Shared/Status.tsx

Hey,
This tiny PR will fix : 
- 1 typo in `apps/web/src/components/Shared/Status.tsx`
Best! :robot:

docs: fix typo in apps/web/src/components/Shared/Status.tsx

---

apps/web/src/components/Home/FeedType.tsx

fix: timeline filter icons in sm screens

---

apps/web/src/components/Settings/Profile/Profile.tsx
packages/lens/documents/queries/Profile.graphql
packages/lens/documents/queries/ProfileSettings.graphql
packages/lens/generated.ts

We dont reset the attributes rather we spread attributes other than that lenster uses....

chore: spread attributes and dont reset

---

apps/web/src/components/Publication/DecryptedPublicationBody.tsx

chore: add token gate auth component

---

apps/web/src/lib/i18n.ts

Reverts lensterxyz/lenster#1490

Revert "fix: dayjs localization"

---

apps/web/src/components/Home/Timeline/EventType/index.tsx
apps/web/src/components/Publication/Actions/Menu/Delete.tsx
apps/web/src/components/Publication/Actions/Menu/Embed.tsx
apps/web/src/components/Publication/Actions/Menu/Report.tsx
apps/web/src/components/Publication/Actions/Menu/index.tsx
apps/web/src/components/Publication/Actions/ModAction.tsx
apps/web/src/components/Publication/PublicationHeader.tsx
apps/web/src/components/Publication/SinglePublication.tsx
apps/web/src/components/Publication/ThreadBody.tsx
apps/web/src/components/Publication/Type/index.tsx

Closes https://github.com/lensterxyz/lenster/issues/1504

fix: expand the publication tap area

---

apps/web/src/components/Common/Layout.tsx
apps/web/src/components/Messages/MessageIcon.tsx
apps/web/src/components/Notification/NotificationIcon.tsx
apps/web/src/components/Shared/Navbar/BottomNavigation.tsx
apps/web/src/components/Shared/Navbar/index.tsx
apps/web/src/styles.css

chore: add bottom navbar and header changes

---

apps/web/src/components/Common/MetaTags.tsx
apps/web/src/components/Shared/Navbar/index.tsx
apps/web/src/styles.css

fix: logo CLS on auth

---

apps/web/src/components/Design/Buttons.tsx
apps/web/src/components/Design/index.tsx
apps/web/src/components/Settings/Interests/Interests.tsx
apps/web/src/components/Settings/Profile/Picture.tsx
apps/web/src/components/UI/Button.tsx

feat: add buttons to design

---

apps/web/src/store/access-settings.ts
apps/web/src/store/app.ts
apps/web/src/store/auth.ts
apps/web/src/store/collect-module.ts
apps/web/src/store/message.ts
apps/web/src/store/modals.ts
apps/web/src/store/profile-feed.ts
apps/web/src/store/publication.ts
apps/web/src/store/reference-module.ts
apps/web/src/store/timeline.ts
apps/web/src/store/transaction.ts

fix: deprecated zustand imports

---

apps/web/src/components/Shared/Attachments.tsx
apps/web/src/components/Shared/Audio/CoverImage.tsx
apps/web/src/components/Shared/Audio/index.tsx

feat: open audio cover in lightbox

---

apps/web/src/components/Publication/Actions/Analytics/index.tsx

chore: add beta batch to analytics modal

---

apps/web/src/components/utils/matchers/UrlMatcher/constants.ts
apps/web/src/components/utils/matchers/UrlMatcher/index.tsx

Fixes #1614
Implementing my own feature request :) @bigint If you don't think this is a good feature, just reject the PR. It was not too much work :)
Write a post with long URL, show the post and confirm that URL is displayed truncated.

fix: show shorter URLs

---

apps/web/src/components/Settings/Profile/Profile.tsx

feat(web): additional `twitter.com` replacement

---

apps/web/src/components/Explore/index.tsx

chore: remove use of emojis in explore page

---

apps/web/src/components/Publication/Actions/Collect/index.tsx
apps/web/src/components/Publication/Actions/Comment.tsx
apps/web/src/components/Publication/Actions/Like.tsx
apps/web/src/components/Publication/Actions/Mirror.tsx
apps/web/src/components/Publication/Actions/index.tsx
apps/web/src/components/Publication/FullPublication.tsx

fix: publication stats in comment feed

---

apps/web/src/components/Explore/index.tsx
apps/web/src/components/Messages/index.tsx
apps/web/src/components/Mod/index.tsx
apps/web/src/components/Notification/index.tsx
apps/web/src/components/Pages/Privacy.tsx
apps/web/src/components/Pages/Terms.tsx
apps/web/src/components/Pages/Thanks.tsx
apps/web/src/components/Profile/New.tsx
apps/web/src/components/Settings/Account/index.tsx
apps/web/src/components/Settings/Allowance/index.tsx
apps/web/src/components/Settings/Cleanup/index.tsx
apps/web/src/components/Settings/Delete/index.tsx
apps/web/src/components/Settings/Dispatcher/index.tsx
apps/web/src/components/Settings/Interests/index.tsx
apps/web/src/components/Settings/Profile/index.tsx
apps/web/src/components/StaffTools/Stats/index.tsx
apps/web/src/locales/en/messages.po
apps/web/src/locales/es/messages.po
apps/web/src/locales/ta/messages.po

feat: add i18n strings to SEO titles

---

apps/web/src/components/Publication/Actions/Like.tsx
apps/web/src/components/Publication/PublicationStats.tsx
apps/web/src/components/Settings/Preferences/LikesPreferences.tsx
apps/web/src/components/Settings/Preferences/index.tsx
apps/web/src/components/Settings/Profile/Profile.tsx
apps/web/src/components/Settings/Sidebar.tsx
apps/web/src/components/Shared/Sidebar.tsx
apps/web/src/locales/en/messages.po
apps/web/src/locales/es/messages.po
apps/web/src/locales/ta/messages.po
apps/web/src/pages/settings/preferences.tsx
apps/web/src/store/preferences.ts
packages/data/constants.ts
packages/data/feature-flags.ts

feat: add reaction count preference

---

apps/web/src/components/Home/index.tsx
apps/web/src/components/Messages/MessageIcon.tsx

Reverts lensterxyz/lenster#1707

Revert "fix: xmtp hotfix"

---

apps/api/src/components/Profile.tsx
apps/api/src/components/Publication.tsx
apps/web/src/lib/imageProxy.ts
package.json
packages/data/constants.ts
packages/data/feature-flags.ts
packages/media-worker/package.json
packages/prerender-worker/package.json

chore: work on better development environment for workers

---

apps/web/src/components/Notification/Type/MirrorNotification.tsx

fix: mirrored message

---

apps/web/src/components/Shared/Audio/CoverImage.tsx

fix: audio post cover image aspect ratio

---

docs/internationalization.md

fix: minor typo

---

apps/web/src/components/Composer/Editor/index.tsx
apps/web/src/components/Shared/Lexical/Plugins/AtMentionsPlugin.tsx

feat: add verified badge in NewMentionsPlugin

---

apps/web/src/components/Publication/OnchainMeta.tsx
packages/lens/documents/fragments/MirrorFields.graphql
packages/lens/generated.ts

feat: show arweave/ipfs hash and collect address on mirrors too

---

packages/data/feature-flags.ts

chore: add chinese testers to gated-locales ff

---

apps/web/src/components/Composer/NewPublication.tsx
apps/web/src/components/Settings/Profile/Profile.tsx
apps/web/src/components/Shared/Status.tsx
packages/data/constants.ts

chore: migrate to ar:// instead of raw gateway url

---

apps/web/src/components/Settings/Sidebar.tsx
packages/data/feature-flags.ts

chore: remove preferences-settings feature flag

---

apps/web/src/components/Shared/Footer/Locale.tsx
apps/web/src/components/Shared/Footer/index.tsx

feat: add locale component

---

apps/web/src/components/Composer/Post/New.tsx
apps/web/src/components/Home/SeeThroughLens.tsx
apps/web/src/components/Home/Timeline/EventType/ProfileCircles.tsx
apps/web/src/components/Messages/MessagesList.tsx
apps/web/src/components/Messages/Preview.tsx
apps/web/src/components/Notification/Profile.tsx
apps/web/src/components/Notification/WalletProfile.tsx
apps/web/src/components/Profile/Details.tsx
apps/web/src/components/Profile/FollowDialog.tsx
apps/web/src/components/Profile/MutualFollowers/index.tsx
apps/web/src/components/Profile/NftGallery/Detail/index.tsx
apps/web/src/components/Settings/Profile/Picture.tsx
apps/web/src/components/Settings/Profile/Profile.tsx
apps/web/src/components/Shared/Attachments.tsx
apps/web/src/components/Shared/Audio/CoverImage.tsx
apps/web/src/components/Shared/IFramely/Embed.tsx
apps/web/src/components/Shared/Navbar/MobileDrawerMenu.tsx
apps/web/src/components/Shared/Navbar/SignedUser.tsx
apps/web/src/components/Shared/SwitchProfiles.tsx
apps/web/src/components/Shared/UserPreview.tsx
apps/web/src/components/Shared/UserProfile.tsx
apps/web/src/components/Shared/WalletProfile.tsx
apps/web/src/components/UI/Image.tsx

fix: image loading infinitely

---

apps/web/src/components/Composer/NewPublication.tsx

fix: imageMimeType in publication metadata if no image is there

---

docs/environment.md

fix: duplicate sentences

---

apps/web/src/components/Shared/IFramely/index.tsx

chore: use nullish coalescing for embed htmls

---

CONTRIBUTING.md

Update Path missleading error in Contributing Document
None

docs: fix CONTRIBUTING doc error path

---

apps/web/src/components/Composer/Actions/CollectSettings/CollectForm.tsx
apps/web/src/components/Composer/Actions/CollectSettings/SplitConfig.tsx

feat: add duplicate address check in MRCM

---

apps/web/src/components/Composer/Actions/CollectSettings/CollectForm.tsx

fix: 0 amount save bug in collect module

---

.gitignore
apps/web/src/components/Shared/Status.tsx

as https://github.com/lensterxyz/lenster/issues/1844 request. we add auto-closed status setting bar feature in this PR
- I have read the [contributing guide](https://github.com/lensterxyz/lenster/blob/main/CONTRIBUTING.md)
- My code follow the style guidelines of this project
- I have performed a self-review of my own code and corrected any misspellings
- I have commented my code, particularly in hard-to-understand areas
- I have checked if my PR needs changes to the documentation
- I have checked if my changes generate no new warnings
- I have added tests that prove my fix is effective or that my feature works
- I have checked if new and existing unit tests pass locally with my changes

chore: auto-closed status setting modal

---

apps/web/src/components/Composer/Actions/CollectSettings/SplitConfig.tsx
packages/data/feature-flags.ts

chore: remove FeatureFlag.MultipleRecipientCollect feature flag

---

apps/web/src/components/Shared/Footer/Locale.tsx
apps/web/src/components/Shared/Login/WalletSelector.tsx
apps/web/src/components/Shared/Navbar/LoginButton.tsx
apps/web/src/tracking.ts

chore: refactor locale and auth events

---

apps/web/src/components/Publication/Actions/Analytics/index.tsx
packages/data/feature-flags.ts

fix: add stats behind feature flag so we will not show broken SA integration

---

apps/web/src/components/Pages/Contact.tsx
packages/data/constants.ts
packages/workers/freshdesk/.dev.vars.example
packages/workers/freshdesk/.eslintrc.js
packages/workers/freshdesk/package.json
packages/workers/freshdesk/src/index.ts
packages/workers/freshdesk/tsconfig.json
packages/workers/freshdesk/wrangler.toml

feat: add freshdesk worker

---

apps/web/src/components/Home/Timeline/EventType/index.tsx
apps/web/src/components/Publication/Actions/Menu/Delete.tsx
apps/web/src/components/Publication/Actions/Menu/Embed.tsx
apps/web/src/components/Publication/Actions/Menu/Report.tsx
apps/web/src/components/Publication/Actions/Menu/index.tsx
apps/web/src/components/Publication/Actions/ModAction.tsx
apps/web/src/components/Publication/Actions/index.tsx
apps/web/src/components/Publication/DecryptedPublicationBody.tsx
apps/web/src/components/Publication/PublicationHeader.tsx
apps/web/src/components/Publication/Type/index.tsx
apps/web/src/components/Shared/Attachments.tsx
apps/web/src/components/Shared/IFramely/Embed.tsx
apps/web/src/components/Shared/Markup/Hashtag.tsx
apps/web/src/components/Shared/Modal/Report/index.tsx
apps/web/src/components/UI/LightBox.tsx
apps/web/src/lib/stopEventPropagation.ts

chore: migrate to stopEventPropagation util

---

apps/prerender/package.json
apps/web/package.json
packages/eslint-config-weblint/package.json
packages/workers/freshdesk/package.json
packages/workers/metadata/package.json
packages/workers/prerender/package.json
packages/workers/sts-generator/package.json
yarn.lock

chore: update yarn dependencies 📦

---

apps/web/src/components/Composer/Actions/ReferenceSettings/index.tsx
apps/web/src/locales/en/messages.po
apps/web/src/locales/es/messages.po
apps/web/src/locales/ta/messages.po
apps/web/src/locales/zh/messages.po

fix: reference module tooltip

---

apps/web/src/components/Shared/UserProfile.tsx

Reverts lensterxyz/lenster#1886

Revert "fix: profile overflow"

---

apps/web/src/components/Shared/UserProfile.tsx

fix: profile name overflow

---

apps/web/src/components/Publication/Actions/Menu/Delete.tsx
apps/web/src/components/Publication/Actions/Menu/index.tsx
apps/web/src/components/Publication/FullPublication.tsx
apps/web/src/locales/en/messages.po
apps/web/src/locales/es/messages.po
apps/web/src/locales/ta/messages.po
apps/web/src/locales/zh/messages.po

Close T-7211
Fixes #1884
https://user-images.githubusercontent.com/69431456/222207850-44ae771a-3834-4c8f-9283-d9337cd6e245.mov

chore: delete publication without reloading the page

---

apps/web/src/components/Common/Layout.tsx
apps/web/src/components/Publication/Actions/Menu/Delete.tsx
apps/web/src/components/Publication/Actions/Menu/index.tsx
apps/web/src/components/Publication/FullPublication.tsx
apps/web/src/components/Shared/Alert/DeletePublication.tsx
apps/web/src/components/Shared/GlobalAlerts.tsx
apps/web/src/components/UI/Alert.tsx
apps/web/src/locales/en/messages.po
apps/web/src/locales/es/messages.po
apps/web/src/locales/ta/messages.po
apps/web/src/locales/zh/messages.po
apps/web/src/store/alerts.ts

feat: migrate publication delete confirmation

---

README.md

This pull request updates the Discord links in the README file to be consistent throughout the documentation. This change improves consistency and reduces the risk of confusion for users.

docs: update discord link for consistency in README.md

---

apps/web/package.json
packages/eslint-config-weblint/package.json
packages/workers/sts-generator/package.json
yarn.lock

chore: update dependencies

---

apps/web/src/components/Shared/IFramely/index.tsx
packages/data/constants.ts

feat: move to selfhosted iframely

---

apps/web/src/components/Mod/Feed.tsx
apps/web/src/components/Mod/index.tsx

feat: add refresh button in mod feed

---

apps/web/src/components/Mod/Feed.tsx
apps/web/src/components/Mod/index.tsx

feat: able to filter by posts, comments and mirrors

---

apps/prerender/package.json
apps/web/package.json
packages/data/package.json
packages/eslint-config-weblint/package.json
packages/workers/curated-profiles/package.json
packages/workers/freshdesk/package.json
packages/workers/metadata/package.json
packages/workers/prerender/package.json
packages/workers/sts-generator/package.json
yarn.lock

chore: update dependencies 📦

---

tests/scripts/apps/prerender/publication.spec.ts

feat: add tests for profile prerender

---

apps/web/src/components/StaffTools/Panels/Profile.tsx
packages/utils/getFollowModule.ts
tests/scripts/packages/utils/getFollowModule.spec.ts
tests/scripts/packages/utils/getIPFSLink.spec.ts

feat: add tests for getFollowModule

---

apps/web/src/apollo.ts
packages/utils/parseJwt.ts
tests/scripts/packages/utils/parseJwt.spec.ts

feat: add tests for parseJwt

---

apps/web/src/components/Publication/PublicationHeader.tsx

chore: make the publication source app logo visible for mods

---

apps/web/src/components/Publication/Actions/Menu/index.tsx
apps/web/src/components/Publication/FullPublication.tsx
apps/web/src/components/Publication/PublicationHeader.tsx
apps/web/src/components/Publication/PublicationStats.tsx
apps/web/src/components/Publication/SinglePublication.tsx
apps/web/src/components/Shared/Attachments.tsx
apps/web/src/components/Shared/Audio/CoverImage.tsx
apps/web/src/components/Shared/Audio/index.tsx
apps/web/src/components/Shared/IFramely/Embed.tsx
apps/web/src/components/Shared/IFramely/Player.tsx
apps/web/src/components/Shared/Modal/Collectors.tsx
apps/web/src/components/Shared/Modal/Likes.tsx
apps/web/src/components/Shared/Modal/Mirrors.tsx
apps/web/src/components/Shared/UserProfile.tsx
apps/web/src/components/Shared/Video.tsx
apps/web/src/components/UI/LightBox.tsx
tests/scripts/apps/prerender/profile.spec.ts
tests/scripts/apps/prerender/publication.spec.ts
tests/scripts/apps/web/contact.spec.ts
tests/scripts/apps/web/explore.spec.ts
tests/scripts/apps/web/home.spec.ts
tests/scripts/apps/web/layout.spec.ts
tests/scripts/apps/web/privacy.spec.ts
tests/scripts/apps/web/profile.spec.ts
tests/scripts/apps/web/publication.spec.ts
tests/scripts/apps/web/terms.spec.ts
tests/scripts/apps/web/utils.spec.ts
tests/scripts/packages/utils/getAvatar.spec.ts

feat: add publications tests

---

apps/web/src/components/Shared/Lexical/withLexicalContext.tsx

chore: fix bold + italic in editor

---

apps/web/src/components/Shared/Markup/MarkupLink/ExternalLink.tsx

fix: url doesn't have protocol

---

packages/data/verified.ts

chore: verify lenstubelogs.lens

---

packages/lens/apollo/cache/createPublicationsFieldPolicy.ts

fix: publication dupes with keyArgs

---

apps/web/src/components/Composer/NewPublication.tsx

Reverts lensterxyz/lenster#2283

Revert "temp: disable dispatcher"

---

apps/web/src/components/Composer/NewPublication.tsx

Reverts lensterxyz/lenster#2293

Revert "chore: pause dispatcher"

---

apps/prerender/src/components/Profile.tsx
tests/scripts/apps/prerender/profile.spec.ts

chore: add profile bio in prerender profile

---

apps/web/public/robots.txt

chore: refactor robots.txt

---

apps/web/src/components/Publication/Actions/Mirror.tsx

fix: mirror throwing prematured toasts

---

packages/lens/.eslintrc.js

fix: add ignorePatterns to avoid errors in generated.ts

---

apps/web/src/components/Composer/Actions/CollectSettings/SplitConfig.tsx
apps/web/src/components/Composer/NewPublication.tsx
apps/web/src/components/Home/SeeThroughLens.tsx
apps/web/src/components/Publication/Actions/Collect/CollectModule.tsx
apps/web/src/components/Publication/Actions/Mirror.tsx
apps/web/src/components/Publication/DecryptedPublicationBody.tsx
apps/web/src/components/Publication/QueuedPublication.tsx
apps/web/src/components/Settings/Profile/index.tsx
apps/web/src/components/Shared/IndexStatus.tsx
apps/web/src/components/Shared/Status.tsx
apps/web/src/components/Shared/SuperFollow/FollowModule.tsx

feat: add proper destructuting of object

---

apps/web/package.json
apps/web/src/components/Publication/PublicationBody.tsx
apps/web/src/components/Shared/Attachments.tsx
apps/web/src/components/Shared/Snapshot/Choices.tsx
apps/web/src/components/Shared/Snapshot/Header.tsx
apps/web/src/components/Shared/Snapshot/index.tsx
packages/lib/formatAddress.ts
packages/lib/getSnapshotProposalId.ts
packages/snapshot/.eslintrc.js
packages/snapshot/apollo/cache.ts
packages/snapshot/apollo/httpLink.ts
packages/snapshot/apollo/index.ts
packages/snapshot/apollo/retryLink.ts
packages/snapshot/apollo/webClient.ts
packages/snapshot/codegen.yml
packages/snapshot/documents/queries/Proposal.graphql
packages/snapshot/generated.ts
packages/snapshot/package.json
packages/snapshot/tsconfig.json

feat: add snapshot integration

---

apps/web/package.json
packages/workers/sts-generator/package.json
yarn.lock

Reverts lensterxyz/lenster#2382

Revert "chore: update dependencies 📦"

---

apps/web/src/components/Publication/ThreadBody.tsx

- change max width for thread body

chore: change max width for thread body

---

apps/web/src/components/Shared/Snapshot/Choices.tsx
apps/web/src/components/Shared/Snapshot/VoteProposal.tsx
apps/web/src/components/Shared/Snapshot/index.tsx
packages/data/feature-flags.ts
packages/snapshot/Snapshot.graphql
packages/snapshot/generated.ts

- feat: ad sign support
- chore: add signature support

feat: snapshot sign support

---

apps/web/src/components/Home/Timeline/EventType/index.tsx
apps/web/src/components/Messages/Preview.tsx
apps/web/src/components/Messages/PreviewList.tsx
apps/web/src/components/Profile/Following.tsx
apps/web/src/components/Profile/MutualFollowers/index.tsx
apps/web/src/components/Publication/Actions/ModAction/index.tsx
apps/web/src/components/Publication/Actions/index.tsx
apps/web/src/components/Publication/PublicationHeader.tsx
apps/web/src/components/Publication/SinglePublication.tsx
apps/web/src/components/Publication/ThreadBody.tsx
apps/web/src/components/Publication/Type/index.tsx
apps/web/src/components/Shared/Attachments.tsx
apps/web/src/components/Shared/Lexical/Plugins/AtMentionsPlugin.tsx
apps/web/src/components/Shared/Lexical/Plugins/EmojiPicker.tsx
apps/web/src/components/Shared/Modal/Report/index.tsx
apps/web/src/components/Shared/Navbar/MobileDrawerMenu.tsx
apps/web/src/components/Shared/Navbar/Search.tsx
apps/web/src/components/Shared/UserPreview.tsx
apps/web/src/components/StaffTools/Panels/MetaDetails.tsx
packages/ui/src/LightBox.tsx

Reverts lensterxyz/lenster#2599

fix: prefer to accompany onClick with some elements

---

apps/web/src/locales/kn/messages.po

Reverts lensterxyz/lenster#2656

Revert "chore(i18n): synchronize translations from crowdin"

---

apps/web/package.json
apps/web/src/components/Publication/RelevantPeople.tsx
apps/web/src/components/Shared/Lexical/Plugins/AutoLinkPlugin.tsx
apps/web/src/components/Shared/Markup/index.tsx
apps/web/src/lib/markupUtils.ts
packages/data/constants.ts
packages/lib/getURLs.ts
pnpm-lock.yaml

Reverts lensterxyz/lenster#2846

Revert "fix: regex denial of service"

---

packages/data/verified.ts

chore: verify pancakesbrah.lens

---

apps/web/package.json
apps/web/src/components/Settings/Export/Fingerprint.tsx
apps/web/src/components/Settings/Export/index.tsx
apps/web/src/locales/en/messages.po
apps/web/src/locales/fr/messages.po
apps/web/src/locales/ru/messages.po
apps/web/src/locales/ta/messages.po
apps/web/src/locales/zh/messages.po
apps/web/src/store/fingerprint.ts
packages/data/storage.ts
yarn.lock

Reverts lensterxyz/lenster#3174

Revert "chore: remove fingerprint"

---

apps/web/src/components/Shared/Navbar/Search.tsx

Adds Debounce to the profile search 
Partially Fixes #53 
🚀

fix: add debounce for profile search

---

apps/web/src/components/Home/RecommendedProfiles.tsx

Removes profile once followed from who to follow list
Fixes #2349 
🚀

fix: removes profile once followed from who to follow list

---

packages/data/staffs.ts

Added bhavya's id here
Added Bhavya's Lenster Id

feat: update staffs.ts

---

apps/web/src/components/Shared/Navbar/Search.tsx

fix: search showing empty state

---

apps/web/src/components/Notification/Type/CollectNotification/index.tsx
apps/web/src/components/Notification/Type/CommentNotification.tsx
apps/web/src/components/Notification/Type/FollowerNotification.tsx
apps/web/src/components/Notification/Type/LikeNotification.tsx
apps/web/src/components/Notification/Type/MentionNotification.tsx
apps/web/src/components/Notification/Type/MirrorNotification.tsx

Fix notification timestamp view
Fixes #3582 
🚀

fix: notification timestamp

---

apps/web/src/components/Messages/Message.tsx
apps/web/src/components/Messages/MessageHeader.tsx
apps/web/src/components/Messages/Preview.tsx
apps/web/src/components/Messages/PreviewList.tsx
apps/web/src/components/Messages/index.tsx
apps/web/src/components/Profile/Details.tsx
apps/web/src/hooks/useMessageDb.tsx
apps/web/src/hooks/useMessagePreviews.tsx
apps/web/src/hooks/useSendOptimisticMessage.tsx
apps/web/src/pages/messages/[...conversationKey].tsx
apps/web/src/pages/messages/index.tsx
apps/web/src/store/message.ts

Reverts lensterxyz/lenster#3748

Revert "fix: dms, removed routing"

---

apps/web/src/components/Publication/FullPublication.tsx
apps/web/src/components/Publication/SinglePublication.tsx
apps/web/src/components/Shared/Shimmer/PublicationShimmer.tsx
apps/web/src/components/Shared/Shimmer/UserProfileShimmer.tsx
apps/web/src/components/Shared/UserProfile.tsx

Reverts lensterxyz/lenster#3734

Revert "feat: reduce avatar size on mobile"

---

.github/workflows/crowdin-download.yml
.husky/pre-commit

Revert "feat: prevent blankline commits"

---

apps/web/src/components/Common/Layout.tsx
apps/web/src/components/Common/Providers/FeatureFlagsProvider.tsx
apps/web/src/components/Common/Providers/PreferencesProvider.tsx
apps/web/src/components/Common/Providers/ProProvider.tsx
apps/web/src/store/useAuthPersistStore.ts
apps/web/src/store/useFeatureFlagsStore.ts
apps/web/src/store/usePreferencesStore.ts
apps/web/src/store/useProStore.ts

Revert "fix: use delMany to clear idb and fix loading states"

---

apps/api/.env.example
apps/api/src/routes/avatar.ts
apps/api/src/utils/constants.ts
apps/web/.env.example

Update environment variables and constants

---

apps/web/src/components/Staff/FeatureFlags/Create.tsx
apps/web/src/components/Staff/FeatureFlags/List.tsx
apps/web/src/components/Staff/Users/Overview/Tool/UpdateFeatureFlags.tsx
packages/lib/api/getAllFeatureFlags.ts
packages/types/hey.d.ts

Fix import and variable names in FeatureFlags components

---

apps/api/src/routes/preference/getPreferences.ts
apps/web/src/components/Common/Providers/PreferencesProvider.tsx
apps/web/src/components/Home/Sidebar/HeyMembershipNft.tsx
apps/web/src/store/non-persisted/useMembershipNftStore.ts
packages/lib/api/getPreferences.ts
packages/types/hey.d.ts

Add membership NFT feature and update preferences

---

apps/api/src/routes/support/create.ts

chore: feat create ticket api

---

apps/api/src/routes/support/create.ts
apps/web/src/components/Shared/Navbar/MobileDrawerMenu.tsx
apps/web/src/components/Shared/Navbar/MoreNavItems.tsx
apps/web/src/components/Shared/Navbar/NavItems/Support.tsx
apps/web/src/components/Support/index.tsx
apps/web/src/pages/support.tsx
packages/ui/src/Select.tsx

feat: add support page

---

apps/web/src/store/non-persisted/useMembershipNftStore.ts

Update dismissedOrMinted value in useMembershipNftStore

---

apps/web/src/components/Publication/Actions/Share/Mirror.tsx
apps/web/src/components/Publication/Actions/Share/UndoMirror.tsx
apps/web/src/components/Publication/Actions/Share/index.tsx
packages/data/tracking.ts

fix: un mirror

---

apps/web/src/components/Publication/PublicationHeader.tsx

Remove unnecessary CSS class in PublicationHeader

---

apps/web/src/components/Publication/Actions/Share/Mirror.tsx
apps/web/src/components/Publication/Actions/Share/UndoMirror.tsx

fix: mirror cache

---

README.md

feat: add open bounties

---

apps/api/src/routes/support/create.ts
apps/web/src/components/Home/Sidebar/HeyMembershipNft.tsx
apps/web/src/components/Publication/HeyOpenActions/Nft/ZoraNft/Mint/index.tsx
apps/web/src/hooks/zora/useZoraNft.ts
packages/lib/nft/getZoraNft.ts
packages/types/nft.d.ts

fix: zora nft rendering

---

packages/lib/nft/getNft.spec.ts
packages/lib/nft/getZoraNft.spec.ts

feat: add zora nft test cases

---

packages/lib/nft/getBasePaintCanvas.spec.ts
packages/lib/nft/getUnlonelyChannel.spec.ts
packages/lib/nft/getUnlonelyNfc.spec.ts

feat: add more nft test cases

---

packages/data/contracts.ts

fix: update ZORA_FIXED_PRICE_SALE_STRATEGY

---

apps/web/src/components/Staff/Overview/Links.tsx

feat: add zendesk tickets link

---

apps/web/src/components/Shared/Alert/BlockOrUnBlockProfile.tsx

fix: block toast message

---

apps/web/package.json
apps/web/src/hooks/useUploadAttachments.tsx
pnpm-lock.yaml

feat: drop exif data and compress image max to 2048hw/1mb

---

apps/web/src/components/Publication/LensOpenActions/CollectModule/CollectAction.tsx
apps/web/src/lib/getAllowanceModule.ts
packages/lens/documents/fragments/OpenActionModulesFields.graphql
packages/lib/allowedOpenActionModules.ts
packages/lib/getCollectModuleData.ts
packages/lib/isOpenActionAllowed.ts

feat: add fee collect module support

---

apps/web/src/components/Publication/LensOpenActions/CollectModule/CollectAction.tsx
apps/web/src/lib/getAllowanceModule.ts
packages/lens/documents/fragments/OpenActionModulesFields.graphql
packages/lib/allowedOpenActionModules.ts
packages/lib/getCollectModuleData.ts

feat: add limited fee collect module support

---

packages/lens/apollo/cache/createProfileActionHistoryFieldPolicy.ts

fix: field policy for profile action history

---

packages/ui/src/ErrorMessage.tsx

feat: add support link to error message component

---

apps/web/src/components/Shared/Navbar/NavItems/Logout.tsx

fix: remove revoke auth while logout, a temp fix for 401

---

.github/workflows/pr-convention.yml

feat: add PR title validation workflow

---

packages/lens/codegen.ts
packages/lens/documents/mutations/profile/ReportProfile.graphql

feat: add reportProfile gql endpoint

---

packages/lens/codegen.ts
packages/lens/documents/mutations/profile/ReportProfile.graphql

revert: "feat: add reportProfile gql endpoint"

---

apps/web/src/components/Composer/LicensePicker.tsx
apps/web/src/components/Composer/NewAttachments.tsx
apps/web/src/components/Composer/NewPublication.tsx
apps/web/src/hooks/usePublicationMetadata.ts
apps/web/src/store/non-persisted/usePublicationStore.ts

feat: add license picker for audio and video

---

apps/web/src/components/Common/Providers/Web3Provider.tsx
packages/lib/getWalletDetails.spec.ts
packages/lib/getWalletDetails.ts

feat: add ledger wallet support

---

apps/web/src/components/Shared/Footer.tsx
packages/data/tracking.ts

chore: replace translate with support

---

apps/web/src/components/Settings/Export/Tokens.tsx

feat: able to copy at and rt

---

apps/web/src/components/Home/FeedType.tsx
apps/web/src/components/Home/PaidActions.tsx
apps/web/src/components/Home/PaidActions/OpenActionPaidAction.tsx
apps/web/src/components/Home/PaidActions/index.tsx
apps/web/src/components/Home/index.tsx
apps/web/src/components/Shared/Shimmer/PaidActionsShimmer.tsx
apps/web/src/components/Shared/SmallUserProfile.tsx
packages/data/enums.ts
packages/data/tracking.ts
packages/lens/apollo/cache/createLatestPaidActionsFieldPolicy.ts
packages/lens/apollo/cache/index.ts
packages/lens/documents/queries/LatestPaidActions.graphql
packages/lib/getCollectModuleData.ts

feat: add paid actions feed

---

apps/web/src/components/Profile/Achievements/Streaks.tsx

fix: react-activity-calendar to make it non scrollable

---

apps/web/src/components/Common/Providers/Web3Provider.tsx

fix: add explorerExcludedWalletIds

---

apps/api/src/db/migrations/20231215171639_dms/migration.sql
apps/api/src/db/schema.prisma
apps/api/src/routes/message/conversation.ts
apps/api/src/routes/message/conversations.ts
apps/api/src/routes/message/messages.ts
apps/api/src/routes/message/send.ts

feat: add dms db and api

---

apps/web/src/components/Composer/NewPublication.tsx

fix: quote not working

---

apps/web/src/components/Shared/Modal/Invites/index.tsx

fix: error margin on invites

---

apps/api/src/routes/internal/leafwatch/stats.ts
apps/web/src/components/Shared/Modal/Invites/index.tsx

- fix: error margin on invites
- feat: add internal leafwatch endpoint

feat: add internal leafwatch endpoint

---

apps/web/src/components/Publication/LensOpenActions/CollectModule/index.tsx

fix: sale ends return null

---

apps/web/src/components/Common/Providers/Web3Provider.tsx
apps/web/src/components/Publication/LensOpenActions/CollectModule/index.tsx
apps/web/src/components/Shared/Login/WalletSelector.tsx
packages/lib/getWalletDetails.ts

- fix: sale ends return null
- fix: firefox login issue

fix: firefox login issue

---

apps/web/src/components/Group/Details.tsx
apps/web/src/components/Publication/FullPublication.tsx
apps/web/src/components/Staff/Overview/EventsToday.tsx
apps/web/src/components/Staff/Overview/ImpressionsToday.tsx
packages/lib/datetime/formatDate.spec.ts
packages/lib/datetime/formatDate.ts
packages/lib/datetime/formatRelativeOrAbsolute.spec.ts
packages/lib/datetime/getNumberOfDaysFromDate.spec.ts
packages/lib/datetime/getTimeAddedNDay.spec.ts
packages/lib/datetime/getTimetoNow.spec.ts

feat: add test cases for date time utils

---

packages/ui/src/Radio.tsx

fix: radio component console error

---

apps/web/src/components/Composer/LinkPreviews.tsx
apps/web/src/components/Composer/NewPublication.tsx
apps/web/src/components/Publication/HeyOpenActions/Nft/BasePaintCanvas/index.tsx
apps/web/src/components/Publication/HeyOpenActions/Nft/UnlonelyChannel/index.tsx
apps/web/src/components/Publication/HeyOpenActions/Nft/UnlonelyNfc/index.tsx
apps/web/src/components/Publication/HeyOpenActions/Nft/ZoraNft/index.tsx
apps/web/src/components/Publication/HeyOpenActions/Nft/index.tsx

feat: add nft link previews

---

apps/web/src/components/Composer/LinkPreviews.tsx
apps/web/src/components/Shared/Oembed/index.tsx

feat: add link oembed previews in composer

---

apps/web/src/components/Publication/HeyOpenActions/Nft/ZoraNft/Mint/index.tsx

feat: add zora nft img on mint modal

---

packages/lens/documents/fragments/publication-metadata/ArticleMetadataV3Fields.graphql
packages/lens/documents/fragments/publication-metadata/AudioMetadataV3Fields.graphql
packages/lens/documents/fragments/publication-metadata/ImageMetadataV3Fields.graphql
packages/lens/documents/fragments/publication-metadata/LinkMetadataV3Fields.graphql
packages/lens/documents/fragments/publication-metadata/LiveStreamMetadataV3Fields.graphql
packages/lens/documents/fragments/publication-metadata/MintMetadataV3Fields.graphql
packages/lens/documents/fragments/publication-metadata/TextOnlyMetadataV3Fields.graphql
packages/lens/documents/fragments/publication-metadata/VideoMetadataV3Fields.graphql
packages/lens/documents/fragments/token-gated/PublicationMetadataLitEncryptionFields.graphql
packages/lens/documents/fragments/token-gated/SecondTierConditionFields.graphql
packages/lens/documents/fragments/token-gated/ThirdTierConditionFields.graphql
packages/lens/documents/fragments/token-gated/criteria/AdvancedContractConditionFields.graphql
packages/lens/documents/fragments/token-gated/criteria/AndConditionFields.graphql
packages/lens/documents/fragments/token-gated/criteria/CollectConditionFields.graphql
packages/lens/documents/fragments/token-gated/criteria/EoaOwnershipConditionFields.graphql
packages/lens/documents/fragments/token-gated/criteria/Erc20OwnershipConditionFields.graphql
packages/lens/documents/fragments/token-gated/criteria/FollowConditionFields.graphql
packages/lens/documents/fragments/token-gated/criteria/NftOwnershipConditionFields.graphql
packages/lens/documents/fragments/token-gated/criteria/OrConditionFields.graphql
packages/lens/documents/fragments/token-gated/criteria/ProfileOwnershipConditionFields.graphql

feat: add token gated fragments

---

apps/web/src/components/Publication/EncryptedPublication/Criteria/SecondTierCondition/index.tsx
apps/web/src/components/Publication/EncryptedPublication/Criteria/ThirdTierCondition/index.tsx
apps/web/src/components/Publication/EncryptedPublication/Criteria/index.tsx
apps/web/src/components/Publication/EncryptedPublication/index.tsx

feat: add basic criteria skeleton with feature flag

---

apps/web/src/components/Publication/EncryptedPublication/Criteria/ProfileOwnershipCondition.tsx
apps/web/src/components/Publication/EncryptedPublication/Criteria/SecondTierCondition/index.tsx
apps/web/src/components/Publication/EncryptedPublication/Criteria/ThirdTierCondition/index.tsx
apps/web/src/components/Publication/EncryptedPublication/index.tsx
apps/web/src/components/Shared/LazySmallUserProfile.tsx

- feat: add ui for profile owner in token gated pub
- fix: remove unwanted props from LazySmallUserProfile

feat: add ui for profile owner in token gated pub

---

packages/lens/documents/fragments/PublicationOperationFields.graphql

feat: add canDecrypt on PublicationOperationFields

---

apps/web/src/components/Publication/EncryptedPublication/Criteria/NftOwnershipCondition.tsx

feat: update NftOwnershipCondition to show avatars and tokens

---

apps/web/src/components/Publication/EncryptedPublication/Criteria/CollectCondition.tsx
apps/web/src/components/Publication/EncryptedPublication/Criteria/ThirdTierCondition/index.tsx

feat: add CollectCondition to token gated pubs

---

apps/web/src/components/Publication/EncryptedPublication/Criteria/FollowCondition.tsx
apps/web/src/components/Publication/EncryptedPublication/Criteria/ProfileOwnershipCondition.tsx
apps/web/src/components/Publication/EncryptedPublication/Criteria/ThirdTierCondition/index.tsx

feat: add FollowCondition to token gated pubs

---

apps/web/src/components/Publication/EncryptedPublication/Criteria/Erc20OwnershipCondition.tsx
apps/web/src/components/Publication/EncryptedPublication/Criteria/ThirdTierCondition/index.tsx

feat: add Erc20OwnershipCondition to token gated pubs

---

apps/web/src/components/Publication/EncryptedPublication/Criteria/index.tsx
apps/web/src/components/Publication/EncryptedPublication/index.tsx

feat: add getCriteria to filter some stuffs on tg pubs

---

apps/web/src/components/Publication/EncryptedPublication/Criteria/index.tsx
apps/web/src/components/Publication/EncryptedPublication/index.tsx

feat: make token gated pub view live

---

apps/web/src/components/Composer/NewPublication.tsx
apps/web/src/components/Pro/index.tsx
apps/web/src/components/Shared/Navbar/MobileDrawerMenu.tsx
apps/web/src/components/Shared/Navbar/SignedUser.tsx
packages/data/feature-flags.ts

cleanup: remove static ff enums

---

apps/web/src/components/Shared/Shimmer/PaidActionsShimmer.tsx

fix: paid action shimmer to use proper height on action context

---

apps/web/src/components/Profile/Cover.tsx
packages/data/constants.ts

fix: reduce cover size of default cover to display more patterns

---

packages/lens/documents/queries/ModuleMetadata.graphql

feat: add ModuleMetadata graphql query

---

apps/web/src/components/Publication/LensOpenActions/UnknownModule/Preview.tsx

feat: consume useModuleMetadataQuery

---

packages/ui/package.json
packages/ui/src/Toggle.tsx
pnpm-lock.yaml

feat: add radix switch for toggle

---

apps/web/src/components/Shared/Login/New/index.tsx
packages/data/regex.ts
packages/data/tests/regex/handle.spec.ts

fix: handle regex and error message

---

packages/data/apps.ts

feat: add yup and t2.world to known apps

---

apps/web/src/components/Publication/EncryptedPublication/Criteria/CollectCondition.tsx
apps/web/src/components/Publication/EncryptedPublication/Criteria/EoaOwnershipCondition.tsx
apps/web/src/components/Publication/EncryptedPublication/Criteria/Erc20OwnershipCondition.tsx
apps/web/src/components/Publication/EncryptedPublication/Criteria/FollowCondition.tsx
apps/web/src/components/Publication/EncryptedPublication/Criteria/NftOwnershipCondition.tsx
apps/web/src/components/Publication/EncryptedPublication/Criteria/ProfileOwnershipCondition.tsx
apps/web/src/components/Publication/EncryptedPublication/Criteria/SecondTierCondition.tsx
apps/web/src/components/Publication/EncryptedPublication/Criteria/ThirdTierCondition.tsx
apps/web/src/components/Publication/EncryptedPublication/Criteria/index.tsx

fix: console errors caused by token gated publications

---

apps/web/src/components/Shared/Oembed/Embed.tsx

fix: make the oembed on mobile small and full width

---

apps/api/src/utils/oembed/meta/generateIframe.ts

feat: support twitch oembed

---

apps/api/src/utils/oembed/getMetadata.ts
apps/api/src/utils/oembed/meta/generateIframe.ts
apps/web/src/components/Shared/Oembed/index.tsx
packages/types/misc.d.ts

fix: add kick live support

---

apps/web/src/lib/profilePictureUtils.ts

fix: add exif cleanup for avatar and cover

---

apps/web/src/components/Search/index.tsx
apps/web/src/components/Settings/Sidebar.tsx
apps/web/src/components/Shared/Sidebar/SidebarMenu.tsx
apps/web/src/components/Shared/Sidebar/SidebarTabs.tsx
apps/web/src/components/Shared/Sidebar/index.tsx
apps/web/src/components/Shared/SidebarMenu.tsx
apps/web/src/components/Staff/Sidebar.tsx

feat: add sidebar menu component

---

apps/api/src/routes/internal/leafwatch/top50Publications.ts

feat: add api that return top 50 posts in the past 24 hrs

---

packages/data/apps.ts

feat: add focalize to known apps

---

apps/og/src/app/posts/[id]/page.tsx

feat: use publication content as description in og

---

apps/og/src/app/posts/[id]/page.tsx

feat: use publication attachments as og images

---

apps/web/src/components/Shared/Badges/Alpha.tsx
apps/web/src/components/Shared/Badges/Beta.tsx
apps/web/src/components/Shared/Badges/New.tsx
packages/ui/src/Badge.tsx

feat: refactor badge component

---

.github/workflows/ci.yml
apps/api/package.json
apps/api/src/routes/ens/index.ts
apps/api/src/utils/constants.ts
apps/api/tests/ens/index.spec.ts
apps/api/vitest.config.ts
apps/web/src/hooks/useEnsName.ts
package.json
pnpm-lock.yaml

feat: add test coverage to: ens/index

---

apps/api/tests/sts/token.spec.ts
apps/api/tests/tba/deployed.spec.ts
apps/api/tests/token/all.spec.ts

feat: add more test cases

---

apps/api/tests/health.spec.ts
apps/api/tests/stats/haveUsedHey.spec.ts
apps/api/tests/stats/profile.spec.ts
apps/api/tests/stats/profileDetails.spec.ts
apps/api/tests/stats/profileImpressions.spec.ts
apps/api/tests/stats/publicationViews.spec.ts
apps/api/tests/stats/streaksCalendar.spec.ts
apps/api/tests/stats/streaksList.spec.ts
apps/api/tests/sts/token.spec.ts
apps/api/tests/tba/deployed.spec.ts
apps/api/tests/token/all.spec.ts

feat: add more api tests

---

apps/web/src/components/Publication/Actions/Menu/index.tsx

fix: hide report pub while logged out

---

apps/web/src/components/Publication/Actions/Menu/Translate.tsx

fix: show translate only if publication have content

---

apps/web/src/components/Profile/MutualFollowers/index.tsx
apps/web/src/components/Shared/UserPreview.tsx

feat: show mutual followers in profile popover

---

packages/lens/documents/fragments/PublicationOperationFields.graphql

chore: remove canDecrypt resolvers

---

apps/web/src/components/Composer/Post/New.tsx
apps/web/src/components/Home/SeeThroughLens.tsx
apps/web/src/components/Notification/Profile.tsx
apps/web/src/components/Profile/Details.tsx
apps/web/src/components/Profile/InvitedBy.tsx
apps/web/src/components/Profile/MutualFollowers/index.tsx
apps/web/src/components/Shared/Navbar/BottomNavigation.tsx
apps/web/src/components/Shared/Navbar/MobileDrawerMenu.tsx
apps/web/src/components/Shared/Navbar/SignedUser.tsx
apps/web/src/components/Shared/SmallUserProfile.tsx
apps/web/src/components/Shared/SwitchProfiles.tsx
apps/web/src/components/Shared/UserPreview.tsx
apps/web/src/components/Shared/UserProfile.tsx

fix: add fallback failure avatars to use lenny instead of placeholder

---

apps/web/src/components/Common/Layout.tsx
apps/web/src/components/Explore/index.tsx
apps/web/src/components/Home/index.tsx
apps/web/src/components/Pages/Privacy.tsx
apps/web/src/components/Pages/Terms.tsx
apps/web/src/components/Pages/Thanks.tsx
apps/web/src/components/Pro/index.tsx
apps/web/src/components/Profile/New.tsx
apps/web/src/components/Search/index.tsx
apps/web/src/components/Shared/Loading.tsx
apps/web/src/components/Shared/PageMetatags.tsx
apps/web/src/components/Support/index.tsx

feat: update metatags

---

LICENSE
packages/data/pride-hashtags.ts
packages/data/tests/regex/hashtag.spec.ts
packages/lib/datetime/formatDate.spec.ts

chore: happy new year!

---

apps/web/package.json
apps/web/src/components/Common/Providers/Web3Provider.tsx
apps/web/src/components/Publication/HeyOpenActions/Nft/BasePaintCanvas/Mint/MintAction.tsx
apps/web/src/components/Publication/HeyOpenActions/Nft/ZoraNft/Mint/MintAction.tsx
apps/web/src/components/Shared/ConnectWallet.tsx
apps/web/src/components/Shared/GlobalModals.tsx
apps/web/src/components/Shared/Login/WalletSelector.tsx
apps/web/src/components/Shared/Login/index.tsx
apps/web/src/components/Shared/Navbar/LoginButton.tsx
apps/web/src/components/Shared/Profile/Follow.tsx
apps/web/src/components/Shared/Profile/Unfollow.tsx
apps/web/src/components/Shared/SuperFollow/index.tsx
apps/web/src/hooks/useLogin.ts
apps/web/src/lib/connectkitTheme.ts
apps/web/src/styles.css
packages/data/tracking.ts
packages/ui/tailwind-preset.ts
pnpm-lock.yaml

feat: migrate to use connectkit

---

apps/api/src/routes/nft/getSoundRelease.ts
apps/web/src/components/Publication/HeyOpenActions/Nft/SoundRelease/Shimmer.tsx
apps/web/src/components/Publication/HeyOpenActions/Nft/SoundRelease/index.tsx
apps/web/src/components/Publication/HeyOpenActions/Nft/UnlonelyNfc/index.tsx
apps/web/src/components/Publication/HeyOpenActions/Nft/index.tsx
apps/web/src/components/Shared/Audio/CoverImage.tsx
apps/web/src/hooks/sound/useSoundRelease.ts
packages/data/tracking.ts
packages/lib/nft/getNft.ts
packages/lib/nft/getSoundRelease.ts
packages/types/nft.d.ts

feat: add sound.xyz nft oa

---

apps/web/src/components/Composer/Post/New.tsx
apps/web/src/components/Publication/Actions/Like.tsx
apps/web/src/components/Publication/Actions/Share/Mirror.tsx
apps/web/src/components/Publication/Actions/Share/Quote.tsx
apps/web/src/components/Publication/index.tsx
apps/web/src/components/Shared/Profile/Follow.tsx
apps/web/src/components/Shared/Profile/Unfollow.tsx
packages/data/errors.ts

feat: add suspended profile restrictions

---

apps/web/src/components/Composer/Actions/CollectSettings/SplitConfig.tsx
apps/web/src/components/Settings/Manager/ProfileManager/AddProfileManager.tsx
apps/web/src/components/Shared/SearchProfiles.tsx
apps/web/src/components/Staff/Users/List.tsx

chore: rename to SearchProfiles

---

apps/web/src/components/Staff/Users/Overview/Tool/ManagedProfiles.tsx
apps/web/src/components/Staff/Users/Overview/Tool/index.tsx

feat: add managed profiles section in staff tools

---

apps/web/src/components/Shared/Audio/index.tsx

feat: add backdrop blur in audio player

---

apps/web/src/components/Composer/Actions/CollectSettings/AmountConfig.tsx
apps/web/src/components/Composer/Actions/CollectSettings/CollectForm.tsx
apps/web/src/components/Composer/Actions/CollectSettings/CollectLimitConfig.tsx
apps/web/src/components/Composer/Actions/CollectSettings/FollowersConfig.tsx
apps/web/src/components/Composer/Actions/CollectSettings/ReferralConfig.tsx
apps/web/src/components/Composer/Actions/CollectSettings/SplitConfig.tsx
apps/web/src/components/Composer/Actions/CollectSettings/TimeLimitConfig.tsx
apps/web/src/components/Settings/Preferences/HighSignalNotificationFilter.tsx
apps/web/src/components/Settings/Preferences/PushNotifications.tsx
apps/web/src/components/Shared/ToggleWithHelper.tsx

feat: redesign collect form settings

---

.github/workflows/cron-clickhouse-cleanup.yml
apps/api/src/routes/internal/cleanup/clickhouse.ts

feat: add clickhouse cleanup cron

---

apps/web/src/components/Pages/Privacy.tsx
apps/web/src/components/Pages/Rules.tsx
apps/web/src/components/Pages/Terms.tsx
apps/web/src/pages/rules.tsx

feat: add rules page

---

apps/api/package.json
apps/api/src/routes/stats/publication/location.ts
apps/web/src/components/Publication/Actions/Views.tsx
apps/web/src/components/Publication/Actions/index.tsx
apps/web/src/components/Publication/PublicationStats.tsx
apps/web/src/components/Shared/GlobalModals.tsx
apps/web/src/components/Shared/Modal/Views.tsx
apps/web/src/store/non-persisted/useGlobalModalStateStore.ts
packages/data/tracking.ts
pnpm-lock.yaml

- feat: add views modal
- feat: add views modal

feat: add views modal

---

apps/web/src/components/Publication/index.tsx
apps/web/src/components/Shared/PublicationWrapper.tsx
apps/web/src/store/non-persisted/useNativeNavigation.ts

feat: add native navigation state

---

apps/api/src/routes/preferences/get.ts
apps/api/tests/preferences/get.spec.ts
apps/web/src/components/Common/Providers/PreferencesProvider.tsx
apps/web/src/components/Notification/List.tsx
apps/web/src/components/Settings/Preferences/HighSignalNotificationFilter.tsx
apps/web/src/components/Settings/Preferences/IsPride.tsx
apps/web/src/components/Shared/Navbar/index.tsx
apps/web/src/store/non-persisted/usePreferencesStore.ts
packages/lib/api/getPreferences.ts
packages/types/hey.d.ts

feat: add isPride and highSignalNotificationFilter on pref root

---

apps/api/src/routes/preferences/get.ts
apps/api/tests/preferences/get.spec.ts
apps/web/src/components/Common/Providers/PreferencesProvider.tsx
apps/web/src/components/Staff/Users/Overview/Tool/Restrictions.tsx
apps/web/src/components/Staff/Users/Overview/Tool/index.tsx
packages/lib/api/getPreferences.ts
packages/types/hey.d.ts

feat: add isFlagged and isSuspended on pref root

---

apps/web/src/components/Home/Timeline/index.tsx

fix: remove slow load of home page

---

apps/web/src/components/Composer/Actions/CollectSettings/index.tsx
apps/web/src/components/Composer/Actions/OpenActionSettings/Config/Tip.tsx
apps/web/src/components/Composer/Actions/OpenActionSettings/OpenActionItem.tsx
apps/web/src/components/Composer/Actions/OpenActionSettings/OpenActionsConfig.tsx
apps/web/src/components/Composer/Actions/OpenActionSettings/OpenActionsList.tsx
apps/web/src/components/Composer/Actions/OpenActionSettings/SaveOrCancel.tsx
apps/web/src/components/Composer/Actions/OpenActionSettings/index.tsx
apps/web/src/components/Composer/NewPublication.tsx
apps/web/src/components/Publication/LensOpenActions/CollectModule/CollectAction.tsx
apps/web/src/components/Publication/LensOpenActions/UnknownModule/Tip/Module.tsx
apps/web/src/components/Publication/LensOpenActions/UnknownModule/Tip/TipAction.tsx
apps/web/src/components/Settings/Allowance/CollectModules.tsx
apps/web/src/components/Settings/Allowance/OpenActions.tsx
apps/web/src/components/Shared/SuperFollow/FollowModule.tsx
apps/web/src/hooks/useActOnUnknownOpenAction.tsx
apps/web/src/store/non-persisted/publication/useOpenActionStore.ts
packages/data/enums.ts
packages/lib/isOpenActionAllowed.ts

feat: create tip

---

apps/web/src/lib/pushToImpressions.ts
packages/ui/src/LightBox.tsx
packages/ui/src/Modal.tsx

fix: dont push impression of the current user

---

apps/web/src/components/Composer/LicensePicker.tsx
apps/web/src/components/Publication/LensOpenActions/UnknownModule/Tip/index.tsx
apps/web/src/components/Publication/Metadata.tsx
packages/data/feature-flags.ts

cleanup: rip lens member feature flag

---

apps/api/package.json
apps/api/src/routes/webhooks/stripe.ts
apps/api/src/server.ts
pnpm-lock.yaml

feat: add stripe api mvp

---

packages/data/constants.ts

feat: add plans

---

apps/web/src/components/Home/Sidebar/RecommendedProfiles.tsx
apps/web/src/components/Home/Sidebar/StaffPicks/index.tsx

chore: update sidebar

---

apps/api/src/db/migrations/20240123080547_add_poll_index/migration.sql
apps/api/src/db/schema.prisma
apps/api/src/routes/polls/create.ts
apps/api/src/routes/polls/get.ts

feat: add poll index

---

apps/api/src/routes/trusted/status.ts
apps/web/src/components/Profile/Details.tsx
apps/web/src/components/Profile/TrustedBadge.tsx
packages/lib/api/getProStatus.ts

feat: add trusted profile status badge

---

apps/og/src/app/posts/[id]/page.tsx
apps/og/src/app/u/[handle]/page.tsx

feat: add profile and post render on OG

---

apps/web/src/components/Bookmarks/index.tsx
apps/web/src/components/Explore/index.tsx
apps/web/src/components/Home/Sidebar/WhoToFollow.tsx
apps/web/src/components/Home/Sidebar/index.tsx

fix: don't use see through profile for WTF

---

apps/api/src/routes/internal/gpt/clickhouse.ts
apps/api/src/utils/createClickhouseClient.ts
apps/web/next.config.js

feat: gpt api

---

apps/web/src/components/Shared/PageMetatags.tsx

Remove duplicate paths in PageMetatags.
N/A

fix: remove duplicate cases

---

packages/lens/apollo/httpLink.ts
packages/lens/package.json
pnpm-lock.yaml

feat: add request id to lens api header

---

apps/api/src/utils/oembed/getMetadata.ts
apps/api/src/utils/oembed/meta/getNft.ts
packages/types/misc.d.ts

- feat: add nft spec on api
- feat: add nft spec on api

feat: add nft spec on api

---

apps/api/src/lib/oembed/getMetadata.ts
apps/api/src/lib/oembed/meta/getPortal.ts
packages/types/misc.d.ts

feat: add portal api mvp

---

apps/api/src/lib/oembed/meta/getNft.ts
apps/api/src/lib/oembed/meta/getPortal.ts
apps/api/tests/oembed/index.spec.ts
packages/types/misc.d.ts

feat: support farcaster frames on hey

---

apps/api/src/db/migrations/20240202154010_add_group_members/migration.sql
apps/api/src/db/schema.prisma
apps/api/src/routes/groups/get.ts
apps/api/src/routes/groups/join.ts
apps/api/src/routes/groups/leave.ts

feat: add join and leave endpoint

---

apps/api/src/routes/groups/get.ts
apps/web/src/components/Group/Details.tsx
apps/web/src/components/Group/Membership.tsx
apps/web/src/components/Group/index.tsx
apps/web/src/components/Shared/Group/Join.tsx
apps/web/src/components/Shared/Group/Leave.tsx
packages/data/tracking.ts
packages/types/hey.d.ts

feat: add membership details and join/leave button

---

apps/api/src/routes/misc/switches.ts
apps/api/src/routes/preferences/get.ts
apps/web/src/components/Common/Providers/KillSwitchProvider.tsx
apps/web/src/components/Common/Providers/PreferencesProvider.tsx
apps/web/src/components/Common/Providers/index.tsx
apps/web/src/lib/isFeatureKilled.ts
apps/web/src/lib/uploadToIPFS.ts
packages/data/feature-flags.ts
packages/lib/api/getPreferences.ts
packages/types/hey.d.ts

refactor: use switches globally

---

apps/web/src/components/Common/Layout.tsx
apps/web/src/components/Home/FeedType.tsx
apps/web/src/components/Home/SeeThroughLens.tsx
apps/web/src/components/Home/Timeline/index.tsx
apps/web/src/store/non-persisted/useTimelineStore.ts
apps/web/src/store/persisted/useProfileStore.ts
packages/data/constants.ts

feat: fallback to hey curated following

---

apps/web/src/components/Settings/Danger/index.tsx
apps/web/src/components/Settings/Manager/index.tsx
apps/web/src/components/Settings/Sidebar.tsx
apps/web/src/components/Shared/Settings/WrongWallet.tsx

fix: show switch wallet instead of 404 in managers and danger zone

---

apps/web/src/components/Shared/Auth/Signup/ChooseHandle.tsx

feat: add handle check

---

apps/api/src/lib/middlewares/validateFeatureAvailable.ts
apps/api/src/routes/groups/create.ts
apps/api/src/routes/groups/favorite.ts
apps/api/src/routes/groups/get.ts
apps/api/src/routes/groups/join.ts
apps/api/src/routes/groups/leave.ts
apps/api/src/routes/groups/unfavorite.ts
apps/web/src/components/Group/Create/index.tsx
apps/web/src/components/Group/Details.tsx
apps/web/src/components/Settings/Profile/Profile.tsx
apps/web/src/pages/-/create-group.tsx
packages/data/constants.ts
packages/data/regex.ts

feat: mvp api for create group

---

apps/api/src/lib/createZendeskClient.ts
apps/api/src/routes/support/create.ts

fix: zendesk tickets

---

apps/web/src/components/Shared/Auth/index.tsx
apps/web/src/components/Shared/GlobalModals.tsx
apps/web/src/components/Staff/Sidebar.tsx
apps/web/src/components/Staff/SignupContract/Balance.tsx
apps/web/src/components/Staff/SignupContract/ProfilesCreated.tsx
apps/web/src/components/Staff/SignupContract/index.tsx
apps/web/src/components/Staff/UI/NumberedStat.tsx
apps/web/src/pages/staff/signup-contract.tsx

- fix: login modal title
- feat: add mini contract page in staff tools

feat: add mini contract page in staff tools

---

apps/web/src/lib/isFeatureAvailable.ts
apps/web/src/lib/isFeatureEnabled.ts
apps/web/src/store/persisted/useFeatureFlagsStore.ts

fix: hydrateKillSwitches

---

apps/api/src/routes/misc/switches.ts
apps/web/src/components/Common/Providers/KillSwitchProvider.tsx
apps/web/src/lib/isFeatureEnabled.ts
apps/web/src/store/persisted/useKillSwitchesStore.ts
packages/data/kill-switches.ts
packages/data/storage.ts

fix: bring back kill switches

---

.gitignore
apps/web/next.config.js
apps/web/package.json
apps/web/sentry.client.config.ts
apps/web/sentry.edge.config.ts
apps/web/sentry.server.config.ts
pnpm-lock.yaml

[ENG-8] feat: add sentry config

---

apps/web/src/components/Shared/Auth/Signup/ChooseHandle.tsx
apps/web/src/components/Shared/Auth/Signup/Moonpay.tsx
packages/data/constants.ts
packages/data/kill-switches.ts

feat: add moonpay

---

apps/web/src/components/Shared/Oembed/Embed.tsx

chore: update embed style

---

apps/web/src/components/Home/Sidebar/WhoToFollow.tsx
apps/web/src/components/Shared/Navbar/NavItems/Logout.tsx
packages/data/tracking.ts

fix: tracking events

---

packages/contracts/README.md
packages/contracts/contracts/HeyLensSignup.sol
packages/contracts/hardhat.config.ts

fix: update contracts

---

apps/web/src/components/Composer/NewPublication.tsx
apps/web/src/components/Publication/Actions/Share/Mirror.tsx
packages/lib/checkDispatcherPermissions.spec.ts
packages/lib/checkDispatcherPermissions.ts

chore: remove momoka beta

---

apps/web/src/components/Publication/Actions/Share/Mirror.tsx
apps/web/src/hooks/useCreatePublication.tsx
apps/web/src/lib/checkAndToastDispatcherError.ts
apps/web/src/lib/errorToast.ts
packages/data/errors.ts

feat: add checkAndToastDispatcherError

---

apps/web/src/components/Mod/FeedType.tsx
apps/web/src/components/Mod/index.tsx
packages/data/enums.ts

chore: rename to TRUSTED_REPORTS

---

apps/web/src/components/Shared/Auth/Signup/ChooseHandle.tsx
packages/data/constants.ts

chore: update paddle details

---

apps/api/src/routes/gardener/report.ts
apps/web/src/components/Publication/Actions/GardenerActions/index.tsx

feat: add gardener report data

---

apps/web/src/components/Profile/Shimmer.tsx

fix: shimmer on profile page

---

apps/web/src/components/Home/Sidebar/StaffPicks/StaffPickedProfile.tsx
apps/web/src/components/Home/Sidebar/WhoToFollow.tsx
apps/web/src/components/Home/Suggested.tsx
apps/web/src/components/Profile/Followers.tsx
apps/web/src/components/Profile/Following.tsx
apps/web/src/components/Profile/index.tsx
apps/web/src/components/Publication/RelevantPeople.tsx
apps/web/src/components/Publication/index.tsx
apps/web/src/components/Search/Profiles.tsx
apps/web/src/components/Shared/Modal/Collectors.tsx
apps/web/src/components/Shared/Modal/Likes.tsx
apps/web/src/components/Shared/Modal/Mirrors.tsx
apps/web/src/components/Shared/Modal/Quotes.tsx
apps/web/src/components/Shared/Navbar/Search.tsx
apps/web/src/components/Shared/UserProfile.tsx
packages/data/tracking.ts
packages/lib/getProfile.ts

feat: add proper source for profile

---

apps/api/package.json
apps/api/src/db/seed.ts
apps/api/src/db/seeds/seedAllowedTokens.ts
apps/api/src/db/seeds/seedFeatureFlags.ts
apps/api/src/db/seeds/seedPreference.ts
apps/api/src/db/seeds/seedProfileFeatures.ts
apps/api/tsconfig.json
apps/api/vitest.config.ts
pnpm-lock.yaml

feat: add prisma clean and seed

---

.github/workflows/ci.yml

feat: add postgres support

---

apps/web/src/components/Profile/Details.tsx
apps/web/src/components/Support/index.tsx

chore: remove copy of profile ID

---

apps/api/src/routes/gardener/reports.ts
apps/api/tests/gardener/reports.spec.ts
apps/web/src/components/Mod/LatestFeed.tsx
apps/web/src/components/Mod/SearchFeed.tsx
apps/web/src/components/Publication/Actions/GardenerActions/index.tsx
apps/web/src/components/Publication/Actions/Mod.tsx
apps/web/src/components/Publication/Actions/index.tsx
apps/web/src/components/Shared/GlobalAlerts.tsx
apps/web/src/store/non-persisted/useGlobalAlertStateStore.ts
packages/lens/documents/fragments/ListProfileFields.graphql
packages/lens/documents/fragments/PublicationOperationFields.graphql
packages/lens/documents/fragments/PublicationProfileFields.graphql

chore: remove has reported from the api

---

apps/web/src/components/Profile/FeedType.tsx
apps/web/src/components/Publication/Actions/GardenerActions/index.tsx
apps/web/src/components/Staff/Users/List.tsx
apps/web/src/components/Staff/Users/Publications.tsx

feat: add publication preview in mod

---

apps/api/src/routes/badges/isHeyProfile.ts

feat: add isHeyProfile badge

---

apps/api/src/lib/oembed/getMetadata.ts
apps/api/src/routes/oembed/index.ts

fix: skipCache for portals for now

---

apps/api/src/routes/internal/features/bulkAssign.ts
apps/web/src/components/Publication/Actions/Share/Mirror.tsx
apps/web/src/components/Publication/OpenAction/CollectModule/CollectAction.tsx
apps/web/src/components/Settings/Account/SuperFollow.tsx
apps/web/src/components/Settings/Danger/Guardian.tsx
apps/web/src/components/Settings/Manager/LensManager/ToggleLensManager.tsx
apps/web/src/components/Settings/Manager/ProfileManager/AddProfileManager.tsx
apps/web/src/components/Shared/Auth/Signup/ChooseHandle.tsx
apps/web/src/components/Shared/Auth/WalletSelector.tsx
apps/web/src/components/Shared/SuperFollow/FollowModule.tsx
apps/web/src/components/Staff/FeatureFlags/Assign.tsx
apps/web/src/components/Staff/FeatureFlags/List.tsx
apps/web/src/hooks/useActOnUnknownOpenAction.tsx
apps/web/src/hooks/useCreatePublication.tsx
packages/data/tracking.ts

- **feat: add bulk assign**
- **feat: add bulk assign**

feat: add bulk assign

---

apps/web/src/components/Profile/CreatorTool.tsx
apps/web/src/components/Profile/Details.tsx
packages/data/constants.ts
packages/data/feature-flags.ts
packages/data/tracking.ts

feat: add creator tool

---

apps/api/src/routes/badges/hasHeyNft.ts
apps/api/src/routes/badges/isHeyProfile.ts
apps/api/src/routes/badges/isTba.ts

fix: add CACHE_AGE_INDEFINITE if true

---

packages/lib/getAssetSymbol.ts
packages/lib/getRedstonePrice.ts

fix: bonsai pricing

---

apps/web/src/components/Publication/OpenAction/CollectModule/CollectAction.tsx
packages/lib/getAssetSymbol.spec.ts

- **fix: test case**
- **chore: add referrers while collect**

chore: add referrers while collect

---

apps/web/src/components/Publication/OpenAction/UnknownModule/Tip/Module.tsx
packages/data/tokens-symbols.ts
packages/lib/getAssetSymbol.ts

feat: add usdEnabled tokens

---

packages/data/allowed-app-for-title.ts
packages/lens/documents/fragments/publication-metadata/ArticleMetadataV3Fields.graphql
packages/lens/documents/fragments/publication-metadata/AudioMetadataV3Fields.graphql
packages/lens/documents/fragments/publication-metadata/ImageMetadataV3Fields.graphql
packages/lens/documents/fragments/publication-metadata/LinkMetadataV3Fields.graphql
packages/lens/documents/fragments/publication-metadata/LiveStreamMetadataV3Fields.graphql
packages/lens/documents/fragments/publication-metadata/MintMetadataV3Fields.graphql
packages/lens/documents/fragments/publication-metadata/TextOnlyMetadataV3Fields.graphql
packages/lens/documents/fragments/publication-metadata/VideoMetadataV3Fields.graphql
packages/lib/getPublicationData.ts

feat: add title only for tape

---

apps/web/package.json
apps/web/src/components/Composer/Editor/index.tsx
apps/web/src/components/Shared/Lexical/Plugins/ImagesPlugin.tsx
pnpm-lock.yaml

feat: add drag and drop support

---

apps/web/src/components/Publication/OpenAction/UnknownModule/Tip/Module.tsx
apps/web/src/components/Publication/OpenAction/UnknownModule/Tip/TipAction.tsx

chore: fix tipping for non usd

---

apps/web/src/components/Composer/Actions/CollectSettings/AmountConfig.tsx
apps/web/src/components/Composer/LicensePicker.tsx
apps/web/src/components/Publication/Metadata.tsx
apps/web/src/components/Publication/OpenAction/UnknownModule/Tip/Module.tsx
apps/web/src/components/Settings/Account/SuperFollow.tsx
apps/web/src/components/Settings/Allowance/CollectModules.tsx
apps/web/src/components/Settings/Allowance/OpenActions.tsx
apps/web/src/components/Shared/Modal/ReportProfile/Reason.tsx
apps/web/src/components/Shared/Modal/ReportPublication/Reason.tsx
apps/web/src/components/Staff/Users/List.tsx
apps/web/src/lib/getAssetLicense.ts
apps/web/src/store/non-persisted/publication/usePublicationLicenseStore.ts
packages/ui/src/Select.tsx

feat: redesign select dropdown

---

apps/web/src/components/Composer/LicensePicker.tsx
packages/ui/src/Select.tsx

feat: update license picker

---

apps/web/src/components/Composer/LinkPreviews.tsx

fix: show only embeds if no attachments

---

apps/api/src/lib/oembed/getMetadata.ts
apps/api/src/lib/oembed/getProxyUrl.ts
apps/api/src/routes/oembed/index.ts

fix: skip luma images from cache

---

apps/web/src/components/Composer/Editor/index.tsx
apps/web/src/components/Shared/Lexical/Plugins/MentionsPlugin.tsx
packages/data/regex.ts

feat: refactor lexical mention plugin

---

apps/web/src/components/Shared/Markup/MarkupLink/Cashtag.tsx
apps/web/src/components/Shared/Markup/MarkupLink/index.tsx
apps/web/src/components/Shared/Markup/index.tsx
packages/data/regex.ts
packages/data/tests/regex/cashtag.spec.ts
packages/data/tracking.ts

feat: add cashtag support

---

apps/web/src/components/Comment/NoneRelevantFeed.tsx
apps/web/src/components/Profile/MutualFollowers/index.tsx
packages/ui/index.ts
packages/ui/src/StackedAvatars.tsx

feat: add stacked avatars in mutual followers and non relevant comments

---

.gitignore
apps/web/next.config.js
apps/web/package.json
apps/web/sentry.client.config.ts
apps/web/sentry.edge.config.ts
apps/web/sentry.server.config.ts
pnpm-lock.yaml

feat: add back sentry

---

apps/web/src/components/Bookmarks/Feed.tsx
apps/web/src/components/Comment/Feed.tsx
apps/web/src/components/Comment/NoneRelevantFeed.tsx
apps/web/src/components/Explore/Feed.tsx
apps/web/src/components/Home/AlgorithmicFeed.tsx
apps/web/src/components/Home/Highlights.tsx
apps/web/src/components/Home/PaidActions/index.tsx
apps/web/src/components/Home/Timeline/index.tsx
apps/web/src/components/Mod/LatestFeed.tsx
apps/web/src/components/Mod/SearchFeed.tsx
apps/web/src/components/Profile/Feed.tsx
apps/web/src/components/Profile/Followers.tsx
apps/web/src/components/Profile/Following.tsx
apps/web/src/components/Profile/MutualFollowers/List.tsx
apps/web/src/components/Publication/Collectors.tsx
apps/web/src/components/Publication/Likes.tsx
apps/web/src/components/Publication/Mirrors.tsx
apps/web/src/components/Publication/Quotes.tsx
apps/web/src/components/Search/Publications.tsx
apps/web/src/styles.css

feat: add virtual scroll on all feeds

---

apps/web/src/components/Home/Sidebar/StaffPicks.tsx
apps/web/src/components/Home/Sidebar/WhoToFollow.tsx
apps/web/src/components/Home/Suggested.tsx
apps/web/src/components/Profile/Followers.tsx
apps/web/src/components/Profile/Following.tsx
apps/web/src/components/Profile/MutualFollowers/List.tsx
apps/web/src/components/Profile/Shimmer.tsx
apps/web/src/components/Publication/Collectors.tsx
apps/web/src/components/Publication/Likes.tsx
apps/web/src/components/Publication/Mirrors.tsx
apps/web/src/components/Publication/RelevantPeople.tsx
apps/web/src/components/Publication/index.tsx
apps/web/src/components/Shared/Profile/FollowUnfollowButton.tsx
apps/web/src/components/Shared/UserProfile.tsx

chore: refactor follow unfollow button

---

apps/api/src/routes/staff-picks/index.ts
apps/api/tests/staff-picks/index.spec.ts
apps/web/src/components/Home/Sidebar/StaffPicks.tsx
apps/web/src/components/Shared/Auth/Login.tsx
packages/lens/documents/queries/StaffPicks.graphql

chore: fix staff picks

---

apps/api/src/lib/oembed/meta/getNft.ts
apps/web/src/components/Shared/Oembed/Nft/index.tsx
packages/lib/getNftChainId.ts
packages/types/misc.d.ts

feat: support frame mint

---

apps/web/src/components/Mod/FeedType.tsx
apps/web/src/components/Mod/Followerings.tsx
apps/web/src/components/Mod/index.tsx
packages/data/enums.ts
packages/lens/apollo/cache/createModFollowersFieldPolicy.ts
packages/lens/apollo/cache/index.ts
packages/lens/documents/queries/ModFollowers.graphql

- **feat: add Followerings page**
- **fix: use arrow**

feat: add mod followerings page

---

apps/api/package.json
apps/api/src/lib/feeds/providers/hey/algorithms/heyMostInteracted.ts
apps/api/src/lib/score/grantScore.ts
apps/api/src/routes/leafwatch/events.ts
apps/web/src/components/Publication/Actions/Like.tsx
apps/web/src/components/Publication/Actions/Menu/Bookmark.tsx
apps/web/src/components/Publication/Actions/Menu/NotInterested.tsx
apps/web/src/components/Publication/Actions/Share/Mirror.tsx
apps/web/src/components/Publication/OpenAction/CollectModule/CollectAction.tsx
apps/web/src/components/Publication/OpenAction/UnknownModule/Tip/Module.tsx
apps/web/src/lib/leafwatch.ts
packages/data/tracking.ts
packages/lib/slugify.ts
pnpm-lock.yaml

- **feat: mvp score system**
- **feat: mvp score system**
- **feat: mvp score system add more events**
- **feat: add more events**
- **feat: add more events**
- **chore: update pointSystemId**

feat: hey score

---

apps/web/src/components/Composer/Actions/OpenActionSettings/OpenActionsList.tsx
apps/web/src/components/Publication/OpenAction/OnBody.tsx

feat: make swap oa public

---

apps/web/src/components/Composer/Actions/OpenActionSettings/Config/Swap/PoolConfig.tsx
apps/web/src/components/Composer/Actions/OpenActionSettings/Config/Swap/RewardConfig.tsx
apps/web/src/components/Composer/Actions/OpenActionSettings/Config/Swap/TokenConfig.tsx
apps/web/src/components/Composer/Actions/OpenActionSettings/Config/Swap/index.tsx
apps/web/src/components/Shared/ToggleWithHelper.tsx
packages/lib/getSwapRewardPool.ts
packages/lib/getUniswapQuote.ts
packages/types/misc.d.ts

- **feat: refactor swap composer**
- **feat: refactor swap composer**

chore: refactor swap oa composer

---

apps/api/src/lib/constants.ts
apps/api/src/routes/avatar.ts
apps/api/src/routes/signup/index.ts
apps/web/src/components/Common/Providers/Web3Provider.tsx
apps/web/src/constants.ts
apps/web/src/hooks/alchemy/getAlchemyNetwork.ts
packages/contracts/README.md
packages/contracts/hardhat.config.ts
packages/contracts/script/deploy.ts
packages/contracts/script/upgrade.ts
packages/data/constants.ts
packages/data/contracts.ts
packages/data/lens-endpoints.ts
packages/lib/getAuthApiHeadersForTest.ts
packages/lib/getNftChainId.ts
packages/lib/getNftChainInfo.ts

chore: upgrade to amoy

---

apps/web/src/components/Bookmarks/Feed.tsx
apps/web/src/components/Explore/Feed.tsx
apps/web/src/components/Home/Timeline/index.tsx
apps/web/src/components/Profile/Feed.tsx
apps/web/src/components/Search/Publications.tsx

feat: scroll position

---

packages/data/apps.ts

feat: add orna.art

---

apps/web/src/components/Shared/Audio/index.tsx

fix: audio player in mobile view

---

apps/web/src/components/Publication/Actions/Share/Quote.tsx

fix: don't show quote modal when unauthd

---

apps/web/src/components/Common/Providers/OptimisticTransactionsProvider.tsx
apps/web/src/components/Profile/Feed.tsx
apps/web/src/store/persisted/useTransactionStore.ts

feat: refetch current profile feed if post got indexed

---

.github/workflows/cron-jobs.yml
apps/api/src/db/migrations/20240418154856_add_draft_publication/migration.sql
apps/api/src/db/migrations/20240418155944_update_attachments/migration.sql
apps/api/src/db/migrations/20240418170947_update_draft/migration.sql
apps/api/src/db/schema.prisma
apps/api/src/routes/drafts/all.ts
apps/api/src/routes/drafts/update.ts
apps/api/src/routes/internal/cron/cleanDraftPublications.ts
apps/api/src/routes/internal/cron/cleanEmailTokens.ts
apps/web/src/components/Composer/Actions/DraftSettings/List.tsx
apps/web/src/components/Composer/Actions/DraftSettings/index.tsx
apps/web/src/components/Composer/NewPublication.tsx
apps/web/src/components/Composer/Post/Discard.tsx
apps/web/src/components/Pro/index.tsx
apps/web/src/components/Staff/FeatureFlags/List.tsx
packages/types/hey.d.ts
packages/ui/src/Alert.tsx

- **feat: add draft publication table**
- **feat: add draft publication table**
- **feat: add create draft endpoint**

feat: add draft support

---

apps/api/src/routes/lens/health.ts
apps/api/src/routes/lens/stats/likes.ts

feat: add likes stats endpoint

---

apps/web/src/components/Common/Providers/PreferencesProvider.tsx
apps/web/src/components/Composer/Actions/CollectSettings/AmountConfig.tsx
apps/web/src/components/Composer/Actions/CollectSettings/CollectForm.tsx
apps/web/src/components/Composer/Actions/DraftSettings/List.tsx
apps/web/src/components/Composer/Actions/Gif/Categories.tsx
apps/web/src/components/Composer/Actions/Gif/Gifs.tsx
apps/web/src/components/Home/Sidebar/StaffPicks.tsx
apps/web/src/components/Profile/Stats/SuperFollowRevenue.tsx
apps/web/src/components/Profile/index.tsx
apps/web/src/components/Publication/OpenAction/CollectModule/index.tsx
apps/web/src/components/Publication/Poll/index.tsx
apps/web/src/components/Settings/Account/SuperFollow.tsx
apps/web/src/components/Settings/Allowance/CollectModules.tsx
apps/web/src/components/Settings/Allowance/OpenActions.tsx
apps/web/src/components/Shared/EmojiPicker/List.tsx
apps/web/src/components/Shared/Oembed/index.tsx
apps/web/src/components/Staff/Users/Overview/Tool/index.tsx
apps/web/src/hooks/useEnsName.ts
apps/web/src/store/persisted/useAllowedTokens.ts
apps/web/src/store/persisted/useFeatureFlagsStore.ts
apps/web/src/store/persisted/useProfileStore.ts
apps/web/src/store/persisted/useSearchStore.ts
apps/web/src/store/persisted/useTransactionStore.ts
apps/web/src/store/persisted/useVerifiedMembersStore.ts
packages/data/storage.ts
packages/lib/api/getAllTokens.ts

feat: move getTokens to state

---

apps/web/src/components/Common/Providers/PreferencesProvider.tsx
apps/web/src/components/Composer/Actions/CollectSettings/AmountConfig.tsx
apps/web/src/components/Profile/Stats/SuperFollowRevenue.tsx
apps/web/src/components/Publication/Actions/Tip/Action.tsx
apps/web/src/components/Publication/Actions/Tip/index.tsx
apps/web/src/components/Publication/Actions/index.tsx
apps/web/src/components/Publication/OpenAction/CollectModule/index.tsx
apps/web/src/components/Settings/Account/SuperFollow.tsx
apps/web/src/components/Settings/Allowance/CollectModules.tsx
apps/web/src/components/Settings/Allowance/OpenActions.tsx
apps/web/src/store/persisted/useAllowedTokens.ts

feat: add bonsai tip

---

apps/web/src/components/Publication/Actions/Tip/Action.tsx
packages/ui/src/Select.tsx

feat: all tokens tip

---

apps/api/src/lib/constants.ts
apps/api/src/routes/sitemap/allPublications.ts
apps/api/src/routes/sitemap/publications.ts
apps/web/next.config.js
apps/web/public/sitemap.xml

feat: add publications sitemap from lens db

---

apps/api/src/routes/lens/rate.ts

feat: add rate endpoint

---

apps/api/package.json
apps/web/package.json
packages/ui/package.json
pnpm-lock.yaml

chore: update deps

---

apps/api/package.json
apps/api/src/routes/sitemap/profileBatches.ts
apps/api/src/routes/sitemap/profiles/[id].ts
apps/api/src/routes/sitemap/publicationBatches.ts
apps/api/src/routes/sitemap/publications/[id].ts
apps/web/.env.example
apps/web/next.config.js
apps/web/public/sitemap.txt
apps/web/public/sitemap.xml
docs/ports.md
pnpm-lock.yaml

feat: migrate to text based sitemap

---

apps/web/src/components/Profile/Details.tsx
apps/web/src/components/Profile/SuspendedDetails.tsx
apps/web/src/components/Profile/index.tsx

feat: add profile suspended view on profile page

---

apps/web/src/components/Profile/index.tsx
apps/web/src/components/Publication/FullPublication.tsx
packages/lib/api/getProfileFlags.ts

feat: hide publication if the og profile author is suspended

---

apps/web/src/components/Home/Sidebar/Gitcoin.tsx

chore: update gitcoin banner

---

apps/api/src/routes/drafts/delete.ts
apps/web/src/components/Composer/Actions/DraftSettings/List.tsx

fix: add delete draft feature

---

apps/api/src/routes/drafts/update.ts
apps/web/src/components/Composer/Actions/DraftSettings/List.tsx
apps/web/src/components/Composer/Post/Discard.tsx
apps/web/src/store/non-persisted/publication/usePublicationStore.ts

feat: add able to update drafts

---

apps/web/src/components/Shared/Attachments.tsx

feat: fix attachments to use assets as well

---

apps/web/src/hooks/usePublicationMetadata.ts

fix: dupe attachments push for images

---

apps/api/src/lib/sitemap/buildSitemap.ts
apps/api/src/lib/sitemap/getLastModDate.ts
apps/api/src/routes/sitemap/profiles/[id].xml.ts
apps/api/src/routes/sitemap/publications.xml.ts
apps/api/src/routes/sitemap/publications/[id].xml.ts

Revert "feat: use clickhouse for fetching publications sitemaps"

---

apps/api/src/routes/sitemap/others.xml.ts
apps/api/src/routes/sitemap/profiles.xml.ts
apps/api/src/routes/sitemap/publications.xml.ts
apps/api/src/routes/sitemap/sitemap.xml.ts
apps/web/public/robots.txt

feat: add others sitemap

---

packages/contracts/contracts/HeyLensSignup/README.md
packages/contracts/contracts/HeyPro/HeyPro.sol
packages/contracts/contracts/HeyPro/README.md
packages/contracts/contracts/HeyTipping/README.md
packages/contracts/hardhat.config.ts
packages/data/constants.ts

chore: update to use amoy scan

---

apps/api/src/routes/lens/score.ts

chore: abstract to use cf workers for hey score

---

apps/api/src/db/migrations/20240424010412_add_cached_profile_score/migration.sql
apps/api/src/db/schema-hey.prisma
apps/api/src/routes/lens/score.ts

feat: add pg cache for score

---

apps/api/src/routes/badges/isHeyProfile.ts

chore: move isHeyProfile badge check to use Lens PG Proxy

---

apps/api/src/db/migrations/20240425020901_add_tip/migration.sql
apps/api/src/db/schema-hey.prisma
apps/api/src/routes/tips/create.ts
packages/data/regex.ts

feat: add tip table and create tip api

---

apps/web/tsconfig.json

Remove some incorrect files in `tsconfig.json`.

chore: cleanup tsconfig.json

---

apps/api/src/data/score-allocations.ts
apps/api/src/routes/score/allocations.ts

feat: add allocations api

---

apps/web/src/components/Composer/Actions/OpenActionSettings/Config/RentableBillboard/CostConfig.tsx
apps/web/src/components/Composer/Actions/OpenActionSettings/Config/RentableBillboard/TimeConfig.tsx
apps/web/src/components/Composer/Actions/OpenActionSettings/Config/RentableBillboard/TokenConfig.tsx
apps/web/src/components/Composer/Actions/OpenActionSettings/Config/RentableBillboard/index.tsx
apps/web/src/components/Composer/Actions/OpenActionSettings/Config/Swap/PoolConfig.tsx
apps/web/src/components/Composer/Actions/OpenActionSettings/OpenActionsConfig.tsx
apps/web/src/components/Composer/Actions/OpenActionSettings/OpenActionsList.tsx
packages/data/enums.ts
packages/data/verified-openaction-modules.ts

- **feat: add mvp rent billboard creation**
- **feat: mvp add encodeAbiParameters**
- **feat: update rentable ui**

feat: add mvp rent billboard creation

---

packages/data/regex.ts

Fixes https://github.com/heyxyz/hey/issues/4890
**Before**
https://github.com/heyxyz/hey/assets/24715727/249612ce-6ee4-4626-9557-b1e51ce775c4
**After**
https://github.com/heyxyz/hey/assets/24715727/42e9cc2b-43fe-4e20-90f8-1b8da3031e50

fix: dismiss the picker after typing space

---

apps/web/src/components/Publication/Actions/Menu/Bookmark.tsx
apps/web/src/components/Publication/Actions/Menu/CopyPostText.tsx
apps/web/src/components/Publication/Actions/Menu/Delete.tsx
apps/web/src/components/Publication/Actions/Menu/HideComment.tsx
apps/web/src/components/Publication/Actions/Menu/NotInterested.tsx
apps/web/src/components/Publication/Actions/Menu/Report.tsx
apps/web/src/components/Publication/Actions/Menu/Share.tsx
apps/web/src/components/Publication/Actions/Menu/Translate.tsx
apps/web/src/components/Publication/Actions/Menu/index.tsx
apps/web/src/components/Publication/Actions/Share/Mirror.tsx
apps/web/src/components/Publication/Actions/Share/Quote.tsx
apps/web/src/components/Publication/Actions/Share/UndoMirror.tsx
apps/web/src/components/Publication/Actions/Share/index.tsx
apps/web/src/components/Publication/Actions/index.tsx
apps/web/src/components/Publication/OpenAction/CollectModule/CollectAction.tsx
apps/web/src/components/Publication/OpenAction/CollectModule/index.tsx
apps/web/src/components/Publication/OpenAction/OnBody.tsx
apps/web/src/components/Publication/OpenAction/index.tsx
apps/web/src/components/Publication/PublicationBody.tsx
apps/web/src/components/Publication/index.tsx
apps/web/src/components/StaffTools/Panels/Publication.tsx
packages/lens/apollo/wsLink.ts

chore: reduce usage of targetPublication

---

apps/api/package.json
apps/api/src/routes/metadata/index.ts
pnpm-lock.yaml

chore: use @lens-protocol/metadata to sign message for protected ids

---

apps/api/src/routes/lens/internal/revenue.ts
apps/web/src/components/Staff/Sidebar.tsx
apps/web/src/components/Staff/Stats/AppRevenue.tsx
apps/web/src/components/Staff/Stats/index.tsx
apps/web/src/pages/staff/stats.tsx

feat: add lens stats page

---

apps/web/src/components/Composer/Actions/CollectSettings/AmountConfig.tsx
apps/web/src/components/Composer/Actions/CollectSettings/CollectLimitConfig.tsx
apps/web/src/components/Composer/Actions/CollectSettings/FollowersConfig.tsx
apps/web/src/components/Composer/Actions/CollectSettings/ReferralConfig.tsx
apps/web/src/components/Composer/Actions/CollectSettings/SplitConfig.tsx
apps/web/src/components/Composer/Actions/DraftSettings/List.tsx
apps/web/src/components/Composer/Actions/Gif/Categories.tsx
apps/web/src/components/Composer/Actions/Gif/Gifs.tsx
apps/web/src/components/Composer/Actions/OpenActionSettings/Config/RentableBillboard/ApproveDelegatedExecutor.tsx
apps/web/src/components/Mod/ReportsFeed/Dispute.tsx
apps/web/src/components/Profile/FeedType.tsx
apps/web/src/components/Publication/Actions/Share/Mirror.tsx
apps/web/src/components/Publication/Actions/Share/UndoMirror.tsx
apps/web/src/components/Settings/Manager/ProfileManager/AddProfileManager.tsx
apps/web/src/components/Shared/Auth/Login.tsx
apps/web/src/components/Staff/FeatureFlags/Assign.tsx
apps/web/src/components/Staff/FeatureFlags/Create.tsx
apps/web/src/components/Staff/Tokens/Create.tsx
apps/web/src/components/Staff/Users/Overview/Tool/UpdateFeatureFlags.tsx

- **fix: set state ts type**
- **fix: set state ts type**
- **fix: set state ts type**
- **fix: set state ts type**
- **fix: set state ts type**
- **fix: set state ts type**
- **fix: set state ts type**
- **fix: set state ts type**

fix: set state ts type

---

apps/web/src/components/Composer/NewPublication.tsx

fix: limit user mentions to 50 on composer

---

apps/web/src/components/Publication/Actions/Menu/Recommend.tsx
apps/web/src/components/Publication/Actions/Menu/index.tsx
packages/data/tracking.ts

feat: add recommend button on publication dropdown

---

apps/web/src/components/Publication/Actions/index.tsx

fix: enable tip for same poster

---

packages/helpers/permit2.spec.ts
packages/helpers/permit2.ts

Handle environment chainId in Permit2 test

fix: permit2 test

---

apps/web/src/components/Publication/OpenAction/UnknownModule/Decent/Module.tsx

Reset approval parameters on Decent NFT mint success

fix: reset signature params on decent txn success

---

apps/web/src/components/Publication/OpenAction/UnknownModule/Decent/Module.tsx

Fixes the actionData loading state and CLS issue on the modal.

fix: loading items and CLS in Decent modal

---

apps/web/src/components/Publication/OpenAction/UnknownModule/Decent/DecentOpenActionPreview.tsx
apps/web/src/components/Publication/OpenAction/UnknownModule/Decent/FeedEmbed.tsx
apps/web/src/components/Publication/OpenAction/UnknownModule/Decent/Module.tsx

> not a biggie, but could we try a slightly bigger blur radius for the bg when you have a moment? and see if it looks better with a transparent light overlay. already looking nice tho!
Fixes Jouni's comment

fix: changing background backdrop in OA previews

---

apps/web/src/components/Publication/OpenAction/UnknownModule/Decent/DecentAction.tsx
apps/web/src/components/Publication/OpenAction/UnknownModule/Decent/FeedEmbed.tsx
apps/web/src/components/Publication/OpenAction/UnknownModule/Decent/Module.tsx

Refactors the way we fetch the actionData. There's now a better separation of uiData and the rest of actionData.
This smoothes the way data is being fetched etc.

fix: refactoring uiData fetching

---

apps/web/src/components/Staff/Users/Overview/Tool/OnchainIdentities.tsx
apps/web/src/components/Staff/Users/Overview/Tool/ProfileOverview.tsx
apps/web/src/components/Staff/Users/Overview/Tool/ProfilePreferences.tsx
apps/web/src/components/Staff/Users/Overview/Tool/index.tsx

feat: add profile preference to staff overview

---

apps/api/src/routes/stats/profile/impressions.ts
apps/web/src/components/Profile/Stats/Impressions.tsx
apps/web/src/components/Profile/Stats/index.tsx

feat: add impressions stats for pro users

---

apps/web/src/components/Home/Sidebar/WhoToFollow.tsx
apps/web/src/components/Publication/MoreRelevantPeople.tsx
apps/web/src/components/Publication/RelevantPeople.tsx

feat: limit mentioned profiles on publication limit to 5 and add more button

---

apps/api/src/routes/lens/internal/stats/signups.ts
apps/web/src/components/Staff/Overview/EventsToday.tsx
apps/web/src/components/Staff/Overview/ImpressionsToday.tsx
apps/web/src/components/Staff/SignupContract/SignupsGraph.tsx
apps/web/src/components/Staff/SignupContract/index.tsx

feat: add signup graph in staff tool

---

apps/web/src/components/Home/FeedType.tsx
apps/web/src/components/Home/index.tsx
apps/web/src/components/Staff/SignupContract/SignupsGraph.tsx

- **fix: lint**
- **fix: make following as default feed instead of for you**

fix: make following as default feed instead of for you

---

apps/web/src/components/Profile/Feed.tsx
apps/web/src/components/Profile/index.tsx
apps/web/src/components/Publication/SinglePublication.tsx

feat: show pinned publication

---

apps/api/src/routes/publications/pin.ts
apps/web/src/components/Common/Providers/PreferencesProvider.tsx
apps/web/src/components/Publication/Actions/Menu/Pin.tsx
apps/web/src/components/Publication/Actions/Menu/index.tsx
apps/web/src/store/non-persisted/useProfileDetailsStore.ts
packages/data/tracking.ts

feat: able to pin post

---

apps/web/src/components/Composer/Actions/CollectSettings/AmountConfig.tsx
apps/web/src/components/Composer/Actions/CollectSettings/CollectForm.tsx
apps/web/src/components/Composer/Actions/CollectSettings/RecipientConfig.tsx
apps/web/src/components/Composer/Actions/CollectSettings/SplitConfig.tsx
apps/web/src/components/Composer/NewPublication.tsx
apps/web/src/components/Publication/Actions/Menu/Recommend.tsx
apps/web/src/components/Publication/RelevantPeople.tsx
packages/helpers/collectModuleParams.spec.ts
packages/helpers/collectModuleParams.ts

feat: add recipient config

---

apps/web/src/components/Home/Sidebar/index.tsx
apps/web/src/components/Profile/Badges/index.tsx

chore: hide membership NFT and badge on non mainnet

---

apps/api/src/helpers/constants.ts
apps/api/src/helpers/oembed/getMetadata.ts
apps/api/src/helpers/oembed/meta/getFrame.ts
apps/api/src/routes/frames/post.ts
apps/api/src/routes/oembed/index.ts
packages/types/misc.d.ts

feat: add mvp open frames api

---

apps/web/src/components/Home/Sidebar/StaffPicks.tsx

fix: cancelled lens api call for staff picks

---

apps/web/src/components/Profile/Menu/CopyAddress.tsx
apps/web/src/components/Profile/Menu/CopyLink.tsx
apps/web/src/components/Profile/Menu/index.tsx
packages/data/tracking.ts

feat: able to copy user address from profile page

---

apps/web/src/components/Mod/ReportsFeed/index.tsx

fix: 500 on mod reports feed

---

apps/web/src/components/Publication/OpenAction/CollectModule/CollectAction.tsx

fix: show collect button always for paid collect module

---

apps/web/src/components/Mod/LatestFeed.tsx

chore: add bigint to skipped profile on mod feed

---

apps/api/package.json
apps/api/src/helpers/score/syncToStack.ts
apps/api/src/routes/score/get.ts
pnpm-lock.yaml

feat: add stack sync score integration

---

apps/api/src/helpers/constants.ts
apps/api/src/helpers/getRpc.ts
apps/api/src/helpers/webhooks/sendSignupNotificationToSlack.ts
apps/api/src/routes/personal/swapToMatic.ts
apps/web/src/components/Common/Providers/Web3Provider.tsx
packages/data/rpcs.ts
packages/data/tests/rpcs.spec.ts
packages/helpers/permit2.ts

Revert "Staging"

---

apps/web/src/components/Shared/Navbar/SiteStatus.tsx
apps/web/src/components/Shared/Navbar/StaffBar/index.tsx
apps/web/src/components/Shared/Navbar/index.tsx

feat: add site status

---

apps/web/src/components/Shared/Oembed/Frames/Transaction.tsx
apps/web/src/components/Shared/Oembed/Frames/index.tsx

feat: add seperate modal for tx frames

---

packages/lens/codegen.ts

feat: add inlineFragmentTypes config

---

apps/api/src/helpers/constants.ts
apps/api/src/routes/internal/leafwatch/profile/details.ts
apps/api/src/routes/internal/leafwatch/profile/haveUsedHey.ts
apps/api/src/routes/internal/leafwatch/profile/impressions.ts
apps/api/src/routes/lens/rate.ts
apps/api/src/routes/lens/stats/profile/all.ts
apps/api/src/routes/score/get.ts
apps/api/src/routes/staff-picks/index.ts
apps/api/src/routes/stats/publication/views.ts

chore: update cache levels

---

apps/web/src/components/Shared/Oembed/Frames/Transaction.tsx
apps/web/src/components/Shared/Oembed/Frames/index.tsx

fix: migrate frames to use zustand

---

apps/web/src/components/Club/index.tsx
apps/web/src/components/Publication/ClubHandle.tsx
apps/web/src/components/Publication/PublicationHeader.tsx
apps/web/src/components/Publication/PublicationProfile.tsx
apps/web/src/components/Shared/ClubPreview.tsx

feat: add club handle in post

---

apps/api/src/routes/clubs/leave.ts
apps/web/src/components/Shared/Club/JoinLeaveButton.tsx
apps/web/src/components/Shared/Club/Leave.tsx

feat: add leave club option

---

apps/api/package.json
apps/api/src/helpers/middlewares/rateLimiter.ts
apps/api/src/helpers/redis.ts
pnpm-lock.yaml

feat: add redis support

---

apps/api/src/helpers/redisClient.ts
apps/api/src/routes/internal/features/assign.ts
apps/api/src/routes/internal/preferences/get.ts
apps/api/src/routes/internal/tokens/create.ts
apps/api/src/routes/internal/tokens/delete.ts
apps/api/src/routes/lens/rate.ts
apps/api/src/routes/meta.ts
apps/api/src/routes/misc/verified.ts
apps/api/src/routes/preferences/get.ts
apps/api/src/routes/preferences/update.ts
apps/api/src/routes/profile/get.ts
apps/api/src/routes/tokens/all.ts
packages/helpers/hoursToSeconds.ts
packages/helpers/minutesToSeconds.ts
packages/helpers/randomNumber.ts

feat: refactor redis

---

apps/api/package.json
apps/api/src/helpers/queue.ts
apps/api/src/helpers/score/calculateAdjustments.ts
apps/api/src/helpers/score/getAndStoreHeyNativeMintNftScore.ts
apps/api/src/helpers/score/getAndStoreHeyZorbNftScore.ts
pnpm-lock.yaml

feat: add bull for queues

---

apps/api/src/helpers/queue.ts

- **chore: change attempts**
- **chore: maxRetriesPerRequest**

cache polls

---

apps/api/package.json
apps/api/src/helpers/queue.ts
apps/api/src/helpers/score/calculateAdjustments.ts
apps/api/src/helpers/score/getAndStoreHeyNativeMintNftScore.ts
apps/api/src/helpers/score/getAndStoreHeyZorbNftScore.ts
pnpm-lock.yaml

feat: add bull queues

---

.github/workflows/ci.yml
.github/workflows/db-migrate.yml
.github/workflows/deploy-docker.yml

Revert "blacksmith.sh: Migrate workflows to Blacksmith"

---

README.md
apps/web/README.md
apps/web/next.config.js
apps/web/src/components/Pages/Thanks.tsx
apps/web/src/components/Shared/Footer.tsx
apps/web/src/components/Shared/Navbar/StaffBar/index.tsx
apps/web/src/components/Staff/Overview/Links.tsx
packages/data/constants.ts
packages/data/tracking.ts

revert: remove vercel

---

apps/api/src/cron/heartbeat.ts
apps/api/src/cron/index.ts

chore: update cron

---

apps/api/package.json
apps/api/src/cron/batchProcessEvents.ts
apps/api/src/cron/batchProcessImpressions.ts
apps/api/src/cron/cleanClickhouse.ts
apps/api/src/routes/internal/leafwatch/profile/details.ts
apps/api/src/routes/internal/leafwatch/profile/haveUsedHey.ts
apps/api/src/routes/internal/leafwatch/profile/impressions.ts
apps/api/src/routes/internal/leafwatch/stats.ts
apps/api/src/routes/invoices/signup.ts
apps/api/src/routes/meta.ts
apps/api/src/routes/stats/profile/impressions.ts
apps/api/src/routes/stats/publication/views.ts
apps/api/src/script/get-invoice-countries.ts
packages/db/.eslintrc.js
packages/db/clickhouseClient.ts
packages/db/env.d.ts
packages/db/package.json
packages/db/tsconfig.json
pnpm-lock.yaml

refactor: migrate clickhouseClient to db

---

apps/api/.env.example
apps/api/Dockerfile
apps/api/env.d.ts
apps/api/package.json
apps/cron/.env.example
apps/cron/package.json
packages/db/clickhouseClient.ts
packages/db/env.d.ts
pnpm-lock.yaml

- **fix: sort**
- **feat: use CLICKHOUSE_URL**
- **chore: rm vite from aoi docker**

chore: rm vite from api docker

---

apps/web/package.json
apps/web/src/components/Messages/Conversations/Conversation.tsx
apps/web/src/components/Messages/Conversations/LatestMessage.tsx
apps/web/src/components/Messages/Conversations/index.tsx
apps/web/src/components/Messages/MessagesList/Message.tsx
pnpm-lock.yaml

- **fix: upgrade xmtp**
- **fix: upgrade xmtp**

fix: upgrade xmtp

---

apps/web/src/components/Design/Buttons.tsx
apps/web/src/components/Design/index.tsx
apps/web/src/components/Messages/MessagesList/Consent.tsx
apps/web/src/components/Profile/Details.tsx
apps/web/src/components/Publication/Actions/HigherActions/GardenerActions.tsx
apps/web/src/components/Settings/Interests/Interests.tsx
apps/web/src/components/Staff/FeatureFlags/List.tsx
apps/web/src/pages/design.tsx
packages/ui/src/Alert.tsx
packages/ui/src/Button.tsx
packages/ui/src/CardHeader.tsx
packages/ui/tailwind-preset.ts

feat: add buttons design

---

apps/web/src/components/Club/Details.tsx
apps/web/src/components/Home/Sidebar/HeyMembershipNft/Mint.tsx
apps/web/src/components/Profile/Details.tsx
apps/web/src/components/Profile/SuspendedDetails.tsx
apps/web/src/components/Publication/OpenAction/CollectModule/index.tsx
apps/web/src/components/Shared/Profile/SuperFollow/FollowModule.tsx

chore: migrate text-2xl to H3

---

apps/web/src/components/Shared/NotLoggedIn.tsx
apps/web/src/pages/404.tsx
apps/web/src/pages/500.tsx

chore: migrate text-3xl to H2

---

apps/web/src/components/Composer/Actions/CollectSettings/SplitConfig.tsx
apps/web/src/components/Composer/NewPublication.tsx
apps/web/src/components/Publication/Actions/Tip/Action.tsx
apps/web/src/components/Publication/PublicationBody.tsx
apps/web/src/components/Settings/Export/Tokens.tsx
apps/web/src/components/Shared/CommentSuspendedWarning.tsx
apps/web/src/components/Shared/CommentWarning.tsx
apps/web/src/components/Shared/MetaDetails.tsx
apps/web/src/components/Shared/Navbar/MoreNavItems.tsx
apps/web/src/components/Shared/Navbar/Search/RecentProfiles.tsx
apps/web/src/components/Shared/Navbar/index.tsx
packages/ui/src/Form.tsx

chore: migrate text-sm to H6

---

apps/web/src/components/Club/Feed.tsx
apps/web/src/components/Composer/Actions/CollectSettings/index.tsx
apps/web/src/components/Explore/Feed.tsx
apps/web/src/components/Mod/LatestFeed.tsx
apps/web/src/components/Mod/SearchFeed.tsx
apps/web/src/components/Notification/FeedType.tsx
apps/web/src/components/Notification/Type/ActedNotification.tsx
apps/web/src/components/Profile/Feed.tsx
apps/web/src/components/Profile/FeedType.tsx
apps/web/src/components/Publication/Actions/index.tsx
apps/web/src/components/Publication/Collectors.tsx
apps/web/src/components/Publication/OpenAction/Collect.tsx
apps/web/src/components/Publication/OpenAction/CollectModule/CollectAction.tsx
apps/web/src/components/Publication/OpenAction/index.tsx
apps/web/src/components/Search/Publications.tsx
apps/web/src/components/Shared/Shimmer/PublicationShimmer.tsx
apps/web/src/components/StaffTools/Panels/Publication.tsx
packages/ui/src/Button.tsx

feat: mvp big collect button

---

apps/web/src/components/Design/Typography.tsx
packages/ui/index.ts
packages/ui/src/Typography.tsx

chore: remove P tag

---

apps/api/package.json
apps/api/src/routes/leafwatch/events.ts
pnpm-lock.yaml

chore: test telemetry-sh

---

apps/api/src/helpers/middlewares/validateSecret.ts
apps/api/src/routes/personal/swapToMatic.ts
apps/api/src/routes/personal/withdrawRewards.ts
apps/api/src/routes/webhooks/pro.ts
apps/api/src/routes/webhooks/signup.ts

feat: add validateSecret middleware

---

apps/web/src/components/Design/AlertDesign.tsx
apps/web/src/components/Design/ButtonsDesign.tsx
apps/web/src/components/Design/ProfilesDesign.tsx
apps/web/src/components/Design/TypographyDesign.tsx
apps/web/src/components/Design/index.tsx

feat: add design system for Alert

---

apps/web/src/components/Design/ModalDesign.tsx
apps/web/src/components/Design/index.tsx

feat: add design system for Modal

---

apps/api/src/helpers/middlewares/validateIsStaff.ts
apps/api/src/routes/drafts/all.ts
apps/api/src/routes/drafts/delete.ts
apps/api/src/routes/drafts/update.ts
apps/api/src/routes/internal/features/all.ts
apps/api/src/routes/internal/features/assign.ts
apps/api/src/routes/internal/features/bulkAssign.ts
apps/api/src/routes/internal/features/create.ts
apps/api/src/routes/internal/features/delete.ts
apps/api/src/routes/internal/features/staffMode.ts
apps/api/src/routes/internal/features/toggle.ts
apps/api/src/routes/internal/preferences/get.ts
apps/api/src/routes/internal/tokens/create.ts
apps/api/src/routes/internal/tokens/delete.ts
apps/api/src/routes/meta.ts
apps/api/src/routes/misc/verified.ts
apps/api/src/routes/polls/act.ts
apps/api/src/routes/preferences/get.ts
apps/api/src/routes/profile/get.ts
apps/api/src/routes/staff-picks/index.ts
apps/api/src/routes/tokens/all.ts
apps/web/src/components/Staff/FeatureFlags/List.tsx
packages/types/hey.d.ts

- **feat: migrate internal ff to prisma**
- **feat: migrate to prisma**
- **feat: migrate to prisma**
- **feat: migrate to prisma**
- **feat: migrate to prisma**
- **feat: migrate to prisma**
- **feat: migrate to prisma**
- **feat: migrate to prisma**
- **feat: migrate to prisma**
- **feat: migrate to prisma**

feat: migrate to prisma

---

apps/api/src/routes/leafwatch/impressions.ts
apps/api/src/routes/meta.ts
apps/cron/src/batchProcessEvents.ts
apps/cron/src/batchProcessImpressions.ts
packages/db/.eslintrc.js
packages/db/.prettierignore

feat: use ts for impressions

---

apps/web/src/components/Publication/OpenAction/UnknownModule/Decent/index.tsx

fixed typo.
availabe -> available

fix: typo on decent toast

---

apps/web/src/components/Home/Sidebar/index.tsx

chore: comment out Gitcoin component in Sidebar for future reference ⚙️

---

pnpm-lock.yaml
script/update-lock-file

- **chore: automate lock file updates with new branch creation and clean install process 🌱📦**
- **chore: update lock file 📦**

chore: update lock file 📦

---

apps/web/package.json
pnpm-lock.yaml

Revert "chore(deps): bump framer-motion from 11.3.29 to 11.3.30"

---

apps/web/package.json
packages/ui/package.json
pnpm-lock.yaml

Revert "chore(deps): bump @headlessui/react from 2.1.2 to 2.1.3"

---

apps/api/package.json
apps/invoice/package.json
apps/web/package.json
packages/helpers/package.json
packages/lens/package.json
pnpm-lock.yaml

Revert "chore(deps): bump axios from 1.7.4 to 1.7.5"

---

pnpm-lock.yaml

Revert "chore: update lock file 📦"

---

apps/web/src/components/Mod/ReportsFeed/ReportDetails.tsx
apps/web/src/components/Staff/Users/ViewReports.tsx

Remove colors from icon in modal title #5214

fix(modal): remove colors from icon in modal title (#5214)

---

apps/api/src/routes/frames/post.ts

Fixes follow-up from issue #5045

feat: add Content-Type to frame POST request

---

apps/web/src/components/Home/FeedType.tsx
apps/web/src/components/Home/index.tsx
apps/web/src/store/persisted/useHomeTabStore.ts
packages/data/storage.ts

Related to #5425
---
For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/heyxyz/hey/issues/5425?shareId=e276b0c7-9214-480a-9606-05136beae1c3).

Remember home page tab preference

---

apps/api/src/routes/internal/profile/get.ts
apps/api/src/routes/preferences/get.ts
apps/api/src/routes/preferences/mute.ts
packages/db/prisma/db/migrations/20241031104627_add_muted_word/migration.sql
packages/db/prisma/db/schema.prisma
packages/helpers/api/getInternalProfile.ts
packages/helpers/api/getPreferences.ts
packages/types/hey.d.ts

Add MutedWord model, migration and endpoints

---

apps/api/src/routes/internal/profile/get.ts
apps/api/src/routes/preferences/get.ts
apps/api/src/routes/preferences/mute.ts
apps/api/src/routes/preferences/unmute.ts
apps/cron/src/clearMutedWords.ts
apps/cron/src/index.ts
apps/web/src/components/Common/Providers/PreferencesProvider.tsx
apps/web/src/components/Publication/EncryptedPublication.tsx
apps/web/src/components/Publication/MutedPublication.tsx
apps/web/src/components/Publication/PublicationBody.tsx
apps/web/src/components/Settings/Preferences/MutedWords.tsx
apps/web/src/components/Settings/Preferences/index.tsx
apps/web/src/store/persisted/usePreferencesStore.ts
packages/data/tracking.ts
packages/types/hey.d.ts

Able to mute words on publications

---

apps/web/src/components/Common/Providers/index.tsx
apps/web/src/components/Publication/Actions/HigherActions/GardenerActions.tsx
apps/web/src/components/Publication/Actions/Menu/Bookmark.tsx
apps/web/src/components/Publication/Actions/Menu/HideComment.tsx
apps/web/src/components/Publication/Actions/Menu/NotInterested.tsx
apps/web/src/components/Publication/Actions/Share/UndoMirror.tsx
apps/web/src/components/Publication/QueuedPublication.tsx
apps/web/src/components/Settings/Interests/Interests.tsx
apps/web/src/components/Settings/Manager/ProfileManager/Managers/List.tsx
apps/web/src/components/Shared/Alert/BlockOrUnBlockProfile.tsx
apps/web/src/components/Shared/Profile/Follow.tsx
apps/web/src/components/Shared/Profile/SuperFollow/FollowModule.tsx
apps/web/src/components/Shared/Profile/Unfollow.tsx
packages/lens/apollo/index.ts

Refactor apollo imports

---

apps/web/src/components/Settings/Export/Tokens.tsx
apps/web/src/components/Staff/Sidebar.tsx
apps/web/src/components/Staff/Sponsorship/Overview.tsx
apps/web/src/components/Staff/Sponsorship/index.tsx
apps/web/src/pages/staff/sponsorship.tsx
packages/indexer/documents/queries/sponsorship/Sponsorship.graphql
packages/indexer/generated.ts
packages/ui/src/NumberedStat.tsx

- **Add sponsors page on staff tools**
- **Add sponsors page on staff tools**

Add sponsors page on staff tools

---

apps/web/src/components/Group/Settings/Overview/Form.tsx
apps/web/src/components/Groups/Sidebar/Create/CreateGroupModal.tsx
apps/web/src/components/Settings/Profile/Account.tsx
apps/web/src/components/Shared/AvatarUpload.tsx

- **Rename to AvatarUpload**
- **Auto save account metadata on avatar and cover upload**

Auto save account metadata on avatar and cover upload

---

apps/api/src/helpers/heyWalletClient.ts
apps/web/package.json
apps/web/src/components/Common/Providers/Web3Provider.tsx
apps/web/src/components/Common/Providers/index.tsx
apps/web/src/components/Post/Actions/Share/Quote.tsx
apps/web/src/components/Post/OpenAction/TipAction/Action.tsx
apps/web/src/components/Shared/Auth/WalletSelector.tsx
apps/web/src/components/Shared/Auth/index.tsx
pnpm-lock.yaml

This pull request includes several changes to improve the integration with the ConnectKit library, refactor the Web3Provider component, and clean up unused imports and code. The most important changes include the integration of ConnectKit, refactoring the Web3Provider component, and cleaning up unused imports.
Integration with ConnectKit:
* [`apps/web/package.json`](diffhunk://#diff-14b60f636e1a2b0061da57aaf231cb1ed15a5dc0c592425ed82e58fec95d42d8R34): Added the ConnectKit library as a dependency.
* [`apps/web/src/components/Common/Providers/Web3Provider.tsx`](diffhunk://#diff-a3dd828a17894321fdb82d5140b9e1061b82bae49196a4f6c01447fb4c586431L1-R56): Integrated ConnectKitProvider with custom themes and configurations for wallet connection.
Refactoring:
* …

feat: Integrate ConnectKit for improved wallet connection experience

---

apps/web/src/components/Composer/NewPublication.tsx
apps/web/src/components/Group/Settings/Overview/Form.tsx
apps/web/src/components/Group/Settings/Rules/ApprovalRule.tsx
apps/web/src/components/Group/Settings/Rules/SuperJoin.tsx
apps/web/src/components/Groups/Sidebar/Create/CreateGroupModal.tsx
apps/web/src/components/Post/Actions/Like.tsx
apps/web/src/components/Post/Actions/Share/Repost.tsx
apps/web/src/components/Post/OpenAction/CollectAction/CollectActionButton.tsx
apps/web/src/components/Post/OpenAction/TipAction/Action.tsx
apps/web/src/components/Settings/Account/SuperFollow.tsx
apps/web/src/components/Settings/Manager/AccountManager/AddAccountManager.tsx
apps/web/src/components/Settings/Manager/LensManager/ToggleLensManager.tsx
apps/web/src/components/Settings/Preferences/AppIcon.tsx
apps/web/src/components/Settings/Preferences/IncludeLowScore.tsx
apps/web/src/components/Settings/Profile/Account.tsx
apps/web/src/components/Settings/Sessions/List.tsx
apps/web/src/components/Shared/Account/Follow.tsx
apps/web/src/components/Shared/Account/Unfollow.tsx
apps/web/src/components/Shared/Alert/BanOrUnbanAccount.tsx
apps/web/src/components/Shared/Alert/BlockOrUnblockAccount.tsx
apps/web/src/components/Shared/Alert/DeletePost.tsx
apps/web/src/components/Shared/Alert/MuteOrUnmuteAccount.tsx
apps/web/src/components/Shared/Auth/Login.tsx
apps/web/src/components/Shared/Auth/Signup/ChooseUsername.tsx
apps/web/src/components/Shared/Group/Join.tsx
apps/web/src/components/Shared/Group/Leave.tsx
apps/web/src/components/Shared/SwitchAccounts.tsx
apps/web/src/helpers/analytics.ts
packages/data/events.ts

- **feat: Add simple analytics events**
- **feat: Add analytics tracking across various user interactions**

feat: Add simple analytics events

---

apps/web/src/components/Account/AccountFeed.tsx

Collects tab shouldn't filter by author.

Fixes query for collected posts in AccountFeed

---

apps/web/src/components/Composer/Actions/CollectSettings/CollectForm.tsx
apps/web/src/components/Group/Settings/Monetize/SuperJoin.tsx
apps/web/src/components/Settings/Danger/Delete.tsx
apps/web/src/components/Settings/Manager/AccountManager/Management/List.tsx
apps/web/src/components/Settings/Monetize/SuperFollow.tsx
apps/web/src/components/Shared/Badges/Alpha.tsx
apps/web/src/components/Shared/UI/Alert.tsx
apps/web/src/components/Shared/UI/Button.tsx

refactor: replace 'danger' variant with 'outline' for buttons

---

apps/web/src/components/Composer/NewPublication.tsx
apps/web/src/components/Group/Settings/Monetize/SuperJoin.tsx
apps/web/src/components/Group/Settings/Personalize/Form.tsx
apps/web/src/components/Groups/Sidebar/Create/CreateGroupModal.tsx
apps/web/src/components/Post/OpenAction/CollectAction/CollectActionButton.tsx
apps/web/src/components/Settings/Danger/Delete.tsx
apps/web/src/components/Settings/Developer/Tokens.tsx
apps/web/src/components/Settings/Funds/Unwrap.tsx
apps/web/src/components/Settings/Funds/Withdraw.tsx
apps/web/src/components/Settings/Funds/Wrap.tsx
apps/web/src/components/Settings/Manager/AccountManager/AddAccountManager.tsx
apps/web/src/components/Settings/Manager/AccountManager/Management/List.tsx
apps/web/src/components/Settings/Manager/AccountManager/Managers/List.tsx
apps/web/src/components/Settings/Manager/Signless.tsx
apps/web/src/components/Settings/Monetize/SuperFollow.tsx
apps/web/src/components/Settings/Personalize/Form.tsx
apps/web/src/components/Settings/Sessions/List.tsx
apps/web/src/components/Settings/Username/LinkUsername.tsx
apps/web/src/components/Settings/Username/UnlinkUsername.tsx
apps/web/src/components/Shared/Account/Follow.tsx
apps/web/src/components/Shared/Account/Fund/TransferFund/Transfer.tsx
apps/web/src/components/Shared/Account/Unfollow.tsx
apps/web/src/components/Shared/Auth/Login.tsx
apps/web/src/components/Shared/AvatarUpload.tsx
apps/web/src/components/Shared/CoverUpload.tsx
apps/web/src/components/Shared/Group/Leave.tsx
apps/web/src/components/Shared/Modal/ReportAccount/index.tsx
apps/web/src/components/Shared/Modal/ReportPost/index.tsx
apps/web/src/components/Shared/UI/Alert.tsx
apps/web/src/components/Shared/UI/Button.tsx

Thanks @sasicodes 🙏🏼 
Issue title looks odd IMO 🤣

feat: motion on button

---

README.md

Hey devs  :)
Enhances README with standard testing and linting instructions to complete the developer workflow documentation. Maintains existing formatting and provides clear commands for test execution and code quality verification.
Thanks for your work!

docs: Add lint commands to build section

---

apps/web/tsconfig.json
apps/web/vite.config.mjs

Revert "Convert to strict TypeScript"

---

apps/api/src/routes/og/ogUtils.ts
apps/api/src/utils/lensPg.ts
apps/api/src/utils/redis.ts
apps/web/src/components/Account/FollowersYouKnowOverview.tsx
apps/web/src/components/Composer/ChooseThumbnail.tsx
apps/web/src/components/Composer/LicensePicker.tsx
apps/web/src/components/Composer/NewPublication.tsx
apps/web/src/components/Post/Actions/Like.tsx
apps/web/src/components/Post/Actions/Menu/Bookmark.tsx
apps/web/src/components/Post/Actions/Menu/Edit.tsx
apps/web/src/components/Post/Actions/Menu/HideComment.tsx
apps/web/src/components/Post/Actions/Menu/NotInterested.tsx
apps/web/src/components/Post/Actions/Share/UndoRepost.tsx
apps/web/src/components/Post/OpenAction/CollectAction/CollectActionButton.tsx
apps/web/src/components/Settings/Funds/TokenOperation.tsx
apps/web/src/components/Settings/Personalize/Form.tsx
apps/web/src/components/Shared/Account/SwitchAccounts.tsx
apps/web/src/components/Shared/Auth/Login.tsx
apps/web/src/components/Shared/Auth/Signup/ChooseUsername.tsx
apps/web/src/components/Shared/Auth/WalletSelector.tsx
apps/web/src/components/Shared/Markup/index.tsx
apps/web/src/components/Shared/Post/Attachments.tsx
apps/web/src/components/Shared/UI/ErrorMessage.tsx
apps/web/src/components/Shared/UI/Form.tsx
apps/web/src/components/Shared/UI/Select.tsx
apps/web/src/hooks/usePostMetadata.tsx
apps/web/src/hooks/useTransactionLifecycle.tsx
biome.json
packages/helpers/getTransactionData.ts

Revert "chore: enforce no explicit any rule"
